### ISSUE TITLE
Dollar sign ($) and RJournal style

### ISSUE THREAD

**Issue by nicolasturaro** [rstudio/rticles#10]
Hi.

When using the dollar sign ($) in a code chunk, knitting as rticles::rjournal_article doesn't parse the code. Using html or pdf_document as output doesn't show the issue.

Accordingly to http://meta.stats.stackexchange.com/questions/1384/markdown-r-code-and-dollar-sign, it seems an old bug of rmarkdown that still keep in rticles.

As described at the link above, putting a $ in the same line, after the comment sign, workaround the issue.

A minimal example of the problem is here: https://github.com/nicolasturaro/R-misc/tree/master/rjournal_issue

Thank you.

**Comment by yihui** [comment]
Fixed. Please try `devtools::install_github('rstudio/rticles')`. Note that it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/
