### ISSUE TITLE
JSS disapproves of JSS style

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rticles#102]
Don't mean to kvetch as the style was indeed most helpful for drafting -- but having submitted we heard back that

>  The manuscript has been written in Markdown using the "rticles" templates. Unfortunately, 
>  these map poorly to the official JSS styles and are unacceptable for entering review. 

rendering it somewhat less perfectly useful.  

/cc @christophsax

**Comment by jjallaire** [comment]
We did the JSS template ~ 4 years ago and at the time it was literally just the JSS LaTeX template from their website with some Pandoc macros added in so it should have been pretty close. Perhaps the template has evolved and we should sync to the new version or perhaps some of the LaTeX generated by Pandoc for basic things like enumerated lists is somehow objectionable?

**Comment by eddelbuettel** [comment]
They are somewhat picky.  @christophsac and I are currently working down a bucket list in a closed repo but maybe we can come back with some ideas.   Fundamentally, though, this is the LaTeX School of Achim (TM) and they really want 'their' macros being used.  I do not know pandoc well enough to be able to tell if we can tweak its arm, or maybe ... postprocess?

**Comment by jjallaire** [comment]
If it was just text substitution of one LaTeX macro for another then we could post-process.

I'd say the first step would be update the template to the latest from JSS (assuming it's changed) then see what issues remain. Note that it is possible to use inline LaTeX rather than markdown (e.g. you could use a `\code{}` macro rather than markdown ``)

**Comment by yihui** [comment]
I think we have mostly resolved the issue in April last year with Achim (via 65a66b513f8e7204ecb92b116758d4834570184b). To quote his final response:

> [...]This looks much better and I think we can work with this. When we notice other issues, we'll let you know.

We haven't heard further complaints since then.
