### ISSUE TITLE
AMS - Figures are not rendered in main pdf

### ISSUE THREAD

**Issue by isezen** [rstudio/rticles#108]
I created a sample of AMS template and rendered it without any modification. I didn't show any figures, but only file names as text. Please, see at the end of the pdf.

[AMS.pdf](https://github.com/rstudio/rticles/files/871453/AMS.pdf)

**Comment by yufree** [comment]
The default layout for AMS rticles template is draft mode, which will only show the name of figures. You could change the layout from `draft` to `twocol` to see the figures in yaml. 

However, if you remove the `draft` in the layout and compile with knitr, you would get error but still the right tex file. Compile the tex file and you would get the PDF with figures to be submitted to AMS. Such issue about hyperlinks in table and figure might be improved in the future.
