### ISSUE TITLE
How to replace the default tex template in rmarkdown::render() function?

### ISSUE THREAD

**Issue by suredream** [rstudio/rticles#112]
Hi Developer:

I found when I click the knitr button actually following command was running:

> pandoc +RTS -K512m -RTS Article.RSE.AFCE30.utf8.md --to latex --from markdown+ascii_identifiers+tex_math_single_backslash-autolink_bare_uris --output myfile.tex --template **/Users/dir/miniconda2/lib/R/library/rticles/rmarkdown/templates/elsevier_article/resources/template.tex** --number-sections --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --bibliography ../ref.bib --filter /Users/dir/miniconda2/bin/pandoc-citeproc

Right now,  I want to move the **rmarkdown/templates/elsevier_article/resources/template.tex** to my current folder and do some minor edits, then specify the new file as the template when run next time. I read the documentation of rmarkdown::render() but didn't found this option.

How to do it?

**Comment by yihui** [comment]
See Section 3.3.7.4: https://bookdown.org/yihui/rmarkdown/pdf-document.html
