### ISSUE TITLE
Guidance on including *.sty files, assumptions about tex environment, and thoughts on travis?

### ISSUE THREAD

**Issue by cboettig** [rstudio/rticles#120]
@jjallaire 

Hi JJ,

Just wanted to get your take on how contributors should be handling dependencies wrt `.sty` files.  

It would be great if the README or package SysReqs gave some more guidelines on what the tex environment should be (i.e. ideally something less comprehensive than texlive-full, which weighs in at >2 GB unpacked). 

Previously I've dropped .sty files that I didn't have in a 'vanilla' tex environment into the template's [skeleton dir](https://github.com/rstudio/rticles/tree/master/inst/rmarkdown/templates/pnas_article/skeleton), though this clutters the user's working directory a bit when they adopt the template.  It would be nice for those sending PRs to know what they should assume visa vi the tex environment, so they can add only the .sty files that are necessary.  (or maybe the assumption is always full texlive and I should never be adding sty files to a PR?)  

Relatedly,  I'd like to make sure our [rocker/verse](https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile#L27-L30) image included the necessary style files to compile any template in `rticles`.  I can do this somewhat manually just by seeing what tests fail on the image of course.  

Lastly, it would be nice to have some automated tests on the repo here, and having a bit more definition on what the tex environment should be would help in setting up the .travis.yml, if you're open to a PR adding a travis file.  That would also set a nice default benchmark for when a contributor should be providing additional .sty files.  

Thanks for your thoughts on this!

**Comment by jjallaire** [comment]
I think the problem of Tex for R / R Markdown is that the users aren't
actively maintaining their Tex libraries but rather using TeX as a black
box dependency. If we want to teach users how to do TeX package management
we can, but I think given the depth and diversity of templates the sanest
thing to do is to just install the full TeX environment.

Another alternative would be for TeX based R Markdown formats to declare
their TeX dependencies, and then have some functions available to install
them in the user TeX library (or even to auto-install them as MikTeX does).
I sadly don't have time to take on something that ambitious right now!

**Comment by dougmet** [comment]
I think this issue covers my question too. I'm starting work on a PR to add [APS journals](https://journals.aps.org/) widely used by the physics community. All of their LaTeX is covered by the [revtex](https://www.ctan.org/pkg/revtex4-1?lang=en) package on CTAN.

If I were to do this would I need to include all necessary dependencies `.sty`, `.bst` and `.cls` from the revtex package into the resources directory? It's not a huge amount of data but might need to check their permission/license situation.

**Comment by dougmet** [comment]
Forget that about license. It's all "The LATEX Project Public Li­cense (LPPL)" of course

**Comment by yihui** [comment]
With TinyTeX, I don't think we will need to worry about this again: https://yihui.name/tinytex/.
