### ISSUE TITLE
How to add a new template into rticles

### ISSUE THREAD

**Issue by suredream** [rstudio/rticles#122]
Hi:

I plan to use rticles to prepare a manuscript to mdpi.

I downloaded [mdpi latex template](http://www.mdpi.com/authors/latex)

I would like to add mdpi template into rticles, if someone can tell me how to do it.

Many thanks,

**Comment by sorenoneill** [comment]
I have a similar issue -- I have created a template for Biomed Central that I would like to contribute

**Comment by jjallaire** [comment]
Take a look at the some of the previous pull requests that added styles:
https://github.com/rstudio/rticles/pulls?q=is%3Apr+is%3Aclosed

**Comment by dleutnant** [comment]
@suredream Did you manage to extend {rticles} with the mdpi template files?

**Comment by dleutnant** [comment]
I'm currently porting the official MDPI template to rticles but need to improve my tex skills at one point (dynamic authors and afilliations, see my [issue](https://github.com/dleutnant/rticles/issues/1)). I think thats the only thing to be done so far. Any support or advice would be greatly appreciated.

**Comment by sorenoneill** [comment]
It's been a while ... so I cant really recall but I think so (more or less) ... see the attached zip and give me a shout if you need help ..


Den 21. december 2017 kl. 07.54.29 +01.00, skrev Dominik Leutnant <notifications@github.com>:

**Comment by dleutnant** [comment]
Sounds promising, but where is the zip file?

**Comment by sorenoneill** [comment]
Ups :-)

Den 22. december 2017 kl. 20.16.13 +01.00, skrev Dominik Leutnant <notifications@github.com>:

**Comment by yihui** [comment]
Thanks, @dleutnant, for #147!

**Comment by dleutnant** [comment]
Thank you, @yihui for all your great packages!!!
