### ISSUE TITLE
Feature Request: Support in Rticles for Using Additional Journals, such as Biometrics

### ISSUE THREAD

**Issue by skywalker26** [rstudio/rticles#125]
I've done some academic writing with the Rticles package and I love it! I'm trying to write a journal article to publish in Biometrics, but am having a difficult time figuring out how I would go about adding in the Biometrics document class and such. Is this something that you'd be open to developing further?

**Comment by dlebauer** [comment]
(I think this issue could be renamed 'how can I contribute a template for a new journal?)

It would be great to have a step-by-step guide to adding a new template. Perhaps this could be added to the package documentation, the README or CONTRIBUTING.md

In addition to the instructions, it could help to have a generic article type - this would serve two purposes: 1) a directory named ``inst/rmarkdown/templates/generic_article` that someone wishing to contribute could copy to `inst/rmarkdown/templates/journalname_article` and 2) for folks who don't want to contribute a template or doesn't know the target submission journal could get started writing a first draft.

Based on a few pull requests, It seems it _should_ be straightforward to add a new template, but perhaps not https://github.com/rstudio/rticles/pull/83 https://github.com/rstudio/rticles/pull/147, PeerJ https://github.com/rstudio/rticles/pull/127

_main content_

* add `journalname_article()` function to R/journalname_article.R 
  * what are requirements here? is this mostly copy-paste and find-replace?
* add inst/rmarkdown/templates/journalname_article/resources/template.tex
  * how to convert a journal provided latex template to a Rmd template? Seems lots of use of `$` to define variables
* add inst/rmarkdown/templates/journalname_article/skeleton/skeleton.Rmd
* add inst/rmarkdown/templates/journalname_article/template.yaml
* which sty / bst / cls / csl etc files to add?   
   * #83 adds natbib.sty - isn't that usually available by default?


_housekeeping_

* Update namespace (could be done by devtools::document()
* update NEWS
* Update README w/ link to supported journal 
* Add tests (what are we testing for?)
   * example: https://github.com/dleutnant/rticles/blob/80fa67ca34f58270dbe2de622d331023e0becd64/tests/testthat/test_formats.R
* gitignore?

**Comment by daltonhance** [comment]
I was able to create Biometrics template in my fork. I used this package of pandoc templates as a starting point: https://github.com/sachsmc/pandoc-journal-templates That package has other statistics journals that wouldn't be too hard to translate to rticles. My fork has all the main content @dlebauer listed, but I would need a little help walking through the housekeeping for a pull request.

**Comment by nuest** [comment]
PR is open at #170

**Comment by oleskiewicz** [comment]
I've just opened #175, I agree that it would have been very helpful to have a contribution guide - maybe a `.github/PULL_REQUEST_TEMPLATE` file (as described [here](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)), with checkboxes from @dlebauer's comment above?

**Comment by yihui** [comment]
A contributing guide has been added: https://github.com/rstudio/rticles/blob/master/.github/PULL_REQUEST_TEMPLATE.md Thanks
