### ISSUE TITLE
sim_article does not appear to \usepackage{longtable}

### ISSUE THREAD

**Issue by Kenkleinman** [rstudio/rticles#126]
I tested by adding

    First Header  | Second Header
    ------------- | -------------
    Content Cell  | Content Cell
    Content Cell  | Content Cell

in the skeleton.Rmd, and got the following error:

! LaTeX Error: Environment longtable undefined.

Error: Failed to compile xxx.tex. See Bins_sim.log for more info.
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "xxx.tex"' had status 1 
Execution halted

Regret I lack the skill to fix myself!

**Comment by yihui** [comment]
Try to add `tables: yes` to YAML.

**Comment by Kenkleinman** [comment]
Tried.  Did not work.  (Sorry if I missed that in the documentation.) 

Is there a cost to adding \usepackage{longtable} to the LaTeX by default?

**Comment by yihui** [comment]
Probably not, but I'm not sure since I'm not familiar with `sim_article`. The contributor of this output format function is the best person to answer this question.

**Comment by ellessenne** [comment]
Hi @Kenkleinman, I am the contributor of the `sim_article` format; pandoc uses `longtable` by default when converting markdown to LaTeX, which is what causes the error. I personally do not like (nor use) long tables, hence I did not hardcode it into the template (I prefer `ctable`). However, you can use the YAML option `header-includes`:

```yaml
---
[...]
header-includes:
- \usepackage{longtable}
---
```

This should solve it - please keep me posted!
Anyway, it shouldn't be too much work to provide a simpler way of using `longtable` as @yihui suggested, if you think it would be useful I can add it!

**Comment by Kenkleinman** [comment]
Hi Allessandro--

Neither the header-includes: syntax you suggest, nor

    output: 
       rticles::sim_article:
          includes:
             in_header: header.tex

works for me.  (Where, obvs., header.tex includes \usepackage{longtable}.)

Upon investigation, the \usepackage{longtable} does not show up in the .tex file.

And, I don't use longtable either!  I think that pandoc must use it by default, at least for tables built by Markdown.   

As I showed above, all I added to your excellent skeleton document was a Markdown table, not a LaTeX longtable environment.  So I think it would probably work best to just add it to the header-- most likely there are others who will either use Markdown tables, or use longtable explicitly and find it hard to get the package included.

**Comment by ellessenne** [comment]
You are right, pandoc translates markdown tables to LaTeX tables using the longtable package - and it is a hardcoded setting. 

This works for me:

```markdown
---
title: A minimal example of markdown tables
author: "A. Uthor\\affilnum{a}"
address:
- num: a
  address: "Department of Incredible Research, University A"
corraddr: some@academic.email.org
authabbr: "Uthor (2017)"
date: 2017
year: 2017
abstract: "A minimal working example"
keywords: Example; Tables;
output: rticles::sim_article
longtable: true
header-includes: 
- \usepackage{longtable}
---

# Introduction

A minimal working example of markdown tables with the Statistics in Medicine R Markdown template

# Table

Table produced by plain markdown:

First Header | Second Header
------------ | -------------
Content cell | Content cell
Content cell | Content cell
```

If it still does not work, then probably you are using the version on CRAN that doesn't allow that yet. Try installing the version on GitHub: `devtools::install_github("rstudio/rticles")`

Anyway, I added an explicit option for including the longtable package and made a new pull request; once incorporated, you will be able to add the option `longtable: true` to the YAML header to load the package.

A.

**Comment by Kenkleinman** [comment]
That did it.  Thanks!  

Is there a strong reason not to just include \usepackage{longtable}?  If the longtable package doesn't introduce conflicts, it seems a pity to put people through this extra step, since it's bound to come up whenever people use the easy (though less pretty) route to making tables.  You'll also have to make it clear how to add the longtable package, since many people will otherwise run into this problem....

**Comment by ellessenne** [comment]
No strong reason to be honest - I just personally don't like how they look, and I would rather be using the `ctable` package (and avoid loading a LaTeX package that is not needed!).
I made a pull request in which I expanded the documentation for the template, it should be easier to understand now (I also put the relevant information in the skeleton document).
