### ISSUE TITLE
Unable to include code in ASA journal article

### ISSUE THREAD

**Issue by aloy** [rstudio/rticles#131]
I'm trying to write an article using the ASA journal template and I am unable to knit if I include any code chunk without setting `include=FALSE` in the chunk option. Is there some reason that I can't do this?

A minimal example is if you open the template and then attempt to run the chunk

````
```
1:10
```
````

**Comment by yihui** [comment]
Not reproducible to me:

![image](https://user-images.githubusercontent.com/163582/42346525-96fadf02-8068-11e8-8692-e545f3db3576.png)

Please elaborate on "unable to knit". Thanks!
