### ISSUE TITLE
Printing issue for JSS style

### ISSUE THREAD

**Issue by benkeser** [rstudio/rticles#132]
I'm running into a situation where printing certain objects does not render to .tex properly. I can't sort out what is causing the error and I'm not certain whether this is an issue with `rticles` or with pandoc. Here's a MWE:

RMD document:

---
author:
  - name: A girl has no name
    affiliation: An affiliation
    address: >
      An address
    email: \email{anemail@aninstitution.edu}
    url: http://website.com
title:
  formatted: '\pkg{apackage}'
  plain:     'apackage'
  short:     'apacakge'
abstract: >
  blah blah blah
keywords:
  formatted: [key1]
  plain:     [key2]
documentclass: jss
classoption: article
output: rticles::jss_article
---

# Introduction
```{r, echo = FALSE, message = FALSE}
if(!("SuperLearner" %in% row.names(installed.packages()))){
  install.packages("SuperLearner")
}
library(SuperLearner)
```
This non-exported function prints fine.

```{r}
SuperLearner:::.SL.require
```
This one does not. 

```{r}
SuperLearner:::predict.SL.glm
```

When I build, the relevant part of the .tex file looks like

```latex
This one does not.

\textbackslash{}begin\{CodeChunk\}

\begin{CodeInput}
R> SuperLearner:::predict.SL.glm
\end{CodeInput}

\textbackslash{}begin\{CodeOutput\} function (object, newdata, \ldots{})
\{ if (is.matrix(newdata)) \{ newdata = as.data.frame(newdata) \} pred
\textless{}- predict(object = object\$object, newdata = newdata, type =
``response'') pred \} \textless{}environment:
namespace:SuperLearner\textgreater{} \textbackslash{}end\{CodeOutput\}
\textbackslash{}end\{CodeChunk\}
```

END RMD DOCUMENT

Any guesses as to why the `\textbackslash{}` is being introduced?

**Comment by yihui** [comment]
Yes, it is caused by the dollar sign. It is a known issue (see #10 and #49), but no one seems to have time to fix it. Technical background: https://github.com/jgm/pandoc/issues/2493

**Comment by JanMarvin** [comment]
Could we add a latex raw attribute to hook_chunks like: ` ```{=latex} ` if not using `kable`? Added that in jss_article, but it breaks if a chunk uses `cache=TRUE`. This should fix the problem above and new a behavior of pandoc 2.0 which treats underscores similar to the dollar sign:

```
# test.Rmd
\begin{foo}
a_b
\end{foo}`
```

```{bash}
pandoc test.Rmd -f markdown+raw_tex -t native
[Para [Str "\\begin{foo}",SoftBreak,Str "a_b",SoftBreak,Str "\\end{foo}"]]
```
previously 
```
pandoc test.Rmd -f markdown+raw_tex -t native
[RawBlock (Format "latex") "\\begin{foo}\na_b\n\\end{foo}"]
```

**Comment by yihui** [comment]
@JanMarvin Thanks! The new [raw attributes](http://pandoc.org/MANUAL.html#generic-raw-attribute) in Pandoc 2.0 sounds like the right way to go.

**Comment by jimvine** [comment]
Until the Pandoc 2.0 solution comes in, this worked for me as an almost workaround, where I had one CodeOutput CodeChunk that had unbalanced $ signs. I added, immediately after it, a CodeChunk with just one dollar sign in it:

```
\begin{CodeChunk}
\begin{CodeOutput}
  # $
\end{CodeOutput}
\end{CodeChunk}
```

(This gets placed after the r code block, in a normal markdown area.)

That does leave a spurious $ on the page, but at least with the # if someone tries to paste it into R it won't do anything! It is, of course, pretty hack-ish, but if I could turn the manual code block white I would almost be happy with this!

With this forcing the actual CodeChunk to be correctly converted into valid LaTeX, I guess that one could use the retained .tex version, strip out this manual hack, and re-compile that to PDF to get a 'clean' version.

**Comment by yihui** [comment]
Fixed. Please try `devtools::install_github('rstudio/rticles')`. Note that it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/
