### ISSUE TITLE
pandoc templates with fewer $$ and more yaml

### ISSUE THREAD

**Issue by baptiste** [rstudio/rticles#133]
While I really like pandoc, I find the way tex templates are written and populated with yaml metadata quite cumbersome. The TeX syntax (for loops, if conditions etc.) is a real hurdle. I'd much rather use R (yaml+knitr/brew/etc.) to extract metadata, process the text, and output raw LaTeX. It's easier to code, easier to maintain and debug, and much more readable.

I developed a proof-of-principle to illustrate this idea: 
https://baptiste.shinyapps.io/headr/
https://github.com/baptiste/headr/blob/master/README.md

With this strategy, the pandoc templates are but minimal; no need to be a TeX expert to produce one. This is potentially orthogonal to `rticles`' current strategies. Ideally the two could coexist, and a user could use one or the other type of template (R-heavy vs TeX-heavy) according to their taste.

**Comment by yihui** [comment]
Thanks for your effort! Personally Pandoc's templating language seems to be simple enough and does not bother me at all. Reinventing it in R seems to be too much work (your TODO list looks big enough already), and I don't know if it will end up as just [yet another standard](https://xkcd.com/927/).

Actually the main tricky thing in my eyes is how you are going to convert Markdown to LaTeX. For example, how will this work?

```yaml
title: "I have got some **Markdown**"
```

The nice thing about Pandoc's native template is that Pandoc will convert everything to the target format (LaTeX, HTML, ...). When you use the `$ $` variables, you don't need to worry about the specific output format.

Personally I don't really see the benefits in the new templating framework, "easier to code, easier to maintain and debug, and much more readable", as you mentioned. If we want to build an output format based on Pandoc, I think Pandoc's native template should be the easiest to maintain (no/little pressure on our shoulders).
