### ISSUE TITLE
Reference works in main body, but not in footnote.

### ISSUE THREAD

**Issue by sierxue** [rstudio/rticles#138]
Rstudio 1.0.153
devtools::install_github("rstudio/rticles")
Elsevier journal style (default, without any modification on the template)

A bib file is used, @keyword, which refers to an article in the bib file, works in the main body but not in footnotes.

**Comment by yihui** [comment]
Not reproducible to me: [elsevier.zip](https://github.com/rstudio/rticles/files/2168100/elsevier.zip)

![image](https://user-images.githubusercontent.com/163582/42346107-1d3792f6-8067-11e8-9df7-f5162ca97dea.png)

Please always provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) when reporting issues. Thanks!
