### ISSUE TITLE
It's better to change access permissions for wiki pages

### ISSUE THREAD

**Issue by yufree** [rstudio/rticles#143]
Spam is [here](https://github.com/rstudio/rticles/wiki/HOW-TO-START-A-BLOG).
Options is [here](https://help.github.com/articles/changing-access-permissions-for-wikis/).

**Comment by yihui** [comment]
Ugh! @jjallaire Could you make me admin of this repo?

**Comment by jjallaire** [comment]
Done!

**Comment by yihui** [comment]
@yufree Thanks for the report! I have disabled the wiki. I don't think we really need it.
