### ISSUE TITLE
Wiley Online Library

### ISSUE THREAD

**Issue by patarol** [rstudio/rticles#155]
Hey guys.

Love your package. I use it a lot to write my papers.
Any chance though to have it also for journals from [Wiley Online Library](http://onlinelibrary.wiley.com)

Thank you

**Comment by nuest** [comment]
The author guidelines mention [Overleaf support](https://authorservices.wiley.com/author-resources/Journal-Authors/Prepare/overleaf/overleaflink.html), so there must be LaTeX templates. However, looking at the spreadsheet [here](https://authorservices.wiley.com/asset/Overleaf_Link_Participating_Journals.xlsx) there are **72** different templates ... would you be willing to find out if there are actual differences between them? Other than that I suggest you create a template for the specific journal you need.

**Comment by yihui** [comment]
For new templates, we are unlikely to create them by ourselves (not enough time or LaTeX expertise or journal publishing experience), but pull requests are welcome! Thanks!
