### ISSUE TITLE
ACM template keep_tex not working.

### ISSUE THREAD

**Issue by tomkom** [rstudio/rticles#168]
I am having troubles to get keep_tex: yes (or true) work with acm_article.

```
output:
  rticles::acm_article 
      keep_tex:true
```

This appears to be missing in the template definition in the acm_template.R

**Comment by yihui** [comment]
@yufree Actually @tomkom didn't format his issue correctly (@tomkom you should use three backticks for code blocks).

**Comment by yihui** [comment]
This is not reproducible to me. Could you try

```r
devtools::install_github('rstudio/rticles')
```

?
