### ISSUE TITLE
rticles Usage

### ISSUE THREAD

**Issue by mattantaliss** [rstudio/rticles#173]
I want to share my experience using rticles in hopes that it will help others or possibly make the usage easier.

I was starting to prepare an article and decided to try using R Markdown for the preparation instead of have R analyses and LaTeX writing as separate pieces. That led me to rticles, but I was met with a variety of error messages when trying to use, for example, elsevier_article. Most of the errors were unrelated to rticles, but the one that really gave me problems was about "elsarticle.cls" not being found.

After making sure I had the latest versions of TeXLive and every package I could find that might be related to this error, I still couldn't get rid of it. I created a separate new document from the Elsevier Journal Article template, and that worked perfectly well. When I copied and pasted the content of that new document to my old one, however, I got the same error.

What this whole issue boiled down to was that I didn't put a copy of "elsarticle.cls" in the same folder as my original document. I was under the impression that by setting the markdown output to be rticles::elsevier_article, it would link to the elsarticle.cls file in the rticles package, and I could not figure out why that file was not being found.

If it's technically possible, I would suggest having rticles automatically pull in/link to the relevant cls file. I would like to be able to change the output type as desired and just have things work, but at least now, I know that when I do such a thing I also need to copy the necessary cls file to the local directory. If it's not technically possible to have that happen automatically, could the README file get an update to note that changing the output type requires the copying of the corresponding cls file into the local folder?

**Comment by yihui** [comment]
Here is how you should get started with the rticles package: https://bookdown.org/yihui/rmarkdown/journals.html

**Comment by mattantaliss** [comment]
That still doesn't say anything about needing to have the cls file in the same folder as the Rmd file.

If I start from a default PDF document or an rticle template and then decide I'd rather use a different rticle template, before earlier today I would not know that I need to copy the cls file into my document's folder since there was no search result or rticle documentation saying so. I assumed the use of an rticle template would mean the location of the necessary cls file (in the rticle folders) would be pointed to during the processing, and the issue I was having was related to an installation problem (since that was the theme of the search results I was getting).

**Comment by yihui** [comment]
I mean Section 13.1 explains the only way to get started with a new article for those who are not familiar with LaTeX: https://bookdown.org/yihui/rmarkdown/rticles-start.html
