### ISSUE TITLE
Adding output formats for not just LaTeX output?

### ISSUE THREAD

**Issue by lwjohnst86** [rstudio/rticles#174]
In my field, most journals only accept Word documents (I know, unfortunate). I have started creating my own (experimental) package ([fost](https://github.com/lwjohnst86/fost)) to make rmarkdown output documents that match requirements from journals in my field. But I feel it would be better to have a single package (aka rticles) that has all the journal formats. 

What is the opinion if I submitted a PR of journal templates for Word document outputs (from my package). Or do the maintainers want this package to only be for LaTeX output?

**Comment by yihui** [comment]
I think we are good with Word templates. There is no need to tie the rticles package to LaTeX.
