### ISSUE TITLE
Please update CRAN

### ISSUE THREAD

**Issue by jekriske-lilly** [rstudio/rticles#178]
The copy of rticles on CRAN is over a year old at this point and not functioning correctly for some workflows whereas the current copy on github works well. 

Are there any plans, in the near future, to update the copy on CRAN?

**Comment by yihui** [comment]
Yes, I'll start working on the CRAN release soon. Thanks for the reminder!

**Comment by yihui** [comment]
On CRAN now: https://cran.rstudio.com/web/packages/rticles/
