### ISSUE TITLE
Cannot knit new R Markdown from Template R Journal Submission

### ISSUE THREAD

**Issue by sbgraves237** [rstudio/rticles#179]
In the current RStudio 1.1.453 with Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko), File > New File > R Markdown > From Template:  R Journal Submission, knit produces the following:  

Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'RJwrapper.tex' failed.
LaTeX errors:
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> texi2dvi
Execution halted

This was after 'install.packages("rticles", type = "source")'.  

What do you suggest I do to diagnose and fix this issue?   

Thanks for your incredibly valuable work on this.  Spencer Graves (sbgraves237)

**Comment by yihui** [comment]
I think I had just fixed it via 56028df8d5fb2b580f6534c0ce155211a37f3514 before you reported the issue. Could you install the development version?

```r
devtools::install_github('rstudio/rticles')
```

**Comment by sbgraves237** [comment]
Yihui Xie just informed me that this problem is fixed in the development version available via:  

devtools::install_github('rstudio/rticles')

Indeed, this got me past this problem.  Thanks again.  Spencer Graves (sbgraves237)
