### ISSUE TITLE
Providing an email address in RSS article causes knit to fail

### ISSUE THREAD

**Issue by jimvine** [rstudio/rticles#186]
Steps to reproduce:

1. Create a new RSS journal document from the template in RStudio.
2. Change the email address line in the YAML header from:

`email: "email (at) address"`

to:

`email: "email@address.com"`

3. Knit

The error I get reads:

> ! Undefined control sequence.
> \hyper@linkurl ...tionraw >>}\relax \Hy@colorlink 
>                                                   \@urlcolor #1\Hy@xspace@en...
> l.38 \begin{document}
> 
> Error: Failed to compile Untitled2.tex. See Untitled2.log for more info.
> In addition: Warning message:
> running command '"pdflatex" -halt-on-error -interaction=batchmode "Untitled2.tex"' had status 1 
> Execution halted

Looking at the related .tex file, I think the key difference is that when a valid email address is provided, the system automatically converts it to this:

`\email{\href{mailto:email@address.com}{\nolinkurl{email@address.com}}}`

Whereas something that's not recognised as an email address is just placed in the email field. Here's what the relevant line of the .tex looks like using the default `email: "email (at) address"` in the YAML header:

`\email{email (at) address}`

(This knits to PDF just fine.)

**Comment by yihui** [comment]
You may escape `@`: `\\@`. See 1269fce.

**Comment by jimvine** [comment]
Thanks!
