### ISSUE TITLE
Trouble with Royal Society Open Science template

### ISSUE THREAD

**Issue by bensprung** [rstudio/rticles#198]
Hi, I get the error 

    pandoc: unrecognized option `--pdf-engine' 

when using the template for Royal Society Open Science. Other rticles templates work fine, as does generic rmarkdown to pdf.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

(For the record, the issue was introduced from #135)

**Comment by bensprung** [comment]
Thanks!!
