### ISSUE TITLE
How to run r code based on yaml data?

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rticles#200]
Is there a way of pre processing yaml data before populating the template? As an example use case, the AGU template needs between 1 and 3 key points that mustn't be longer than 100 characters. It would be neat to throw a warning if they don't comply to this specification.

**Comment by yihui** [comment]
It is relatively easy to do this inside the Rmd document: all YAML metadata is available via `rmarkdown::metadata`. You could check `any(nchar(metadata$keypoints) > 100)`.
