### ISSUE TITLE
Cannot get the author and affiliation lines to show.

### ISSUE THREAD

**Issue by cownr10r** [rstudio/rticles#205]
This is not necessarily a bug. However, when I fill in the appropriate information and try to print out the PLOS article format using a command to deliver a word_document, I cannot get the author and affiliation lines to show. However, the document will otherwise render. Can someone help?
<img width="654" alt="screen shot 2019-01-07 at 1 38 44 am" src="https://user-images.githubusercontent.com/7209507/50754931-fd537480-121c-11e9-8dc6-e810c0c5e88e.png">

<img width="455" alt="screen shot 2019-01-07 at 1 37 35 am" src="https://user-images.githubusercontent.com/7209507/50754889-d6953e00-121c-11e9-8acc-d5480424f466.png">

**Comment by yihui** [comment]
`word_document` does not support affiliation, and it doesn't support the `author` field in YAML that contains lists (only supports a plain vector of authors).

The `plos_article` template is for LaTeX output only, and won't magically work for Word output (most fields in YAML header will be lost).
