### ISSUE TITLE
关于Pandoc 在 Mac OS X的安装

### ISSUE THREAD

**Issue by harryprince** [rstudio/rticles#22]
```sudo tlmgr install collection-fontsrecommended```才可以执行.
```tlmgr install collection-fontsrecommended```不可以执行.

**Comment by yihui** [comment]
如果是我们在任何地方误导了你，请指出来源，我们好更新，否则的话，我不太明白你开此帖是什么意思（到底是要提醒别人，还是说我们什么地方说错了）。

另外，sudo不一定是必须的，取决于你是怎么安装LaTeX的，如果你没有通过sudo安装LaTeX，那么安装LaTeX包的时候也不需要sudo。是否需要用sudo是系统软件管理的基本知识，还望补习一下。
