### ISSUE TITLE
Add IMS templates

### ISSUE THREAD

**Issue by alexpghayes** [rstudio/rticles#234]
Would love to be able to write papers for Annals of Applied Statistics in R markdown

**Comment by yihui** [comment]
Thanks for the request! Most templates in this package are contributed by users, so either you or someone else has to do the work and send a pull request.

**Comment by cderv** [comment]
@alexpghayes FYI as you were interested by this template.
You may know a bit about this Journal and you could be interested to test @auzaheta great PR.
