### ISSUE TITLE
PeerJ output text appears cut

### ISSUE THREAD

**Issue by elrobin** [rstudio/rticles#237]
---

I am having issues when knitting to peerj format. Part of the text of some pages appears cut maybe due to the inclusion of figures? No error message or anything comes from it.

Here I attach a screenshot.

![screenshot](https://user-images.githubusercontent.com/8256263/60719549-52501900-9f28-11e9-9180-178f719cc813.PNG)

Many thanks in advance and also for creating and maintaining this awesome package!!

**Comment by yihui** [comment]
Cc @zkamvar (for #127).

**Comment by zkamvar** [comment]
Second on the reproducible example. I think one of the first places to check is to see if you get the same behavior on another computer.

**Comment by elrobin** [comment]
Sorry for that, yes, the problem seems to be solved. I updated the package and have no problems now
