### ISSUE TITLE
pnas_article() doesn't work with certain latest LaTeX packages

### ISSUE THREAD

**Issue by yihui** [rstudio/rticles#241]
Today `pnas_article()` [started to fail on Travis](https://travis-ci.org/rstudio/rticles/builds/574386134#L2416), with an obscure error message

```
! LaTeX Error: Missing \begin{document}.
``` 

I could reproduce the issue locally after I update all LaTeX packages via

```r
remotes::install_github('yihui/tinytex')
tinytex::tlmgr_update()
```

Even the following minimal LaTeX example fails with the same error message:

```tex
\documentclass{pnas-new}
\begin{document}
a
\end{document}
```

I spent a few hours on this issue but couldn't figure out why it was broken. I wonder if it is time to consider updating `pnas-new.cls` now.

Cc @cboettig (author of `pnas_article()` #72).

**Comment by eddelbuettel** [comment]
> I wonder if it is time to consider updating pnas-new.cls now.

That's what we did as our PNAS derivative [pinp](https://github.com/eddelbuettel/pinp) failed at CRAN:  https://github.com/eddelbuettel/pinp/issues/77

I got some rather decent debugging help from Kurt pointing to, in this case, issues with [titlesec](https://github.com/jbezos/titlesec/) so we filed https://github.com/jbezos/titlesec/issues/16 -- as we initially missed the newer `pnas-new.cls` that Debian's texlive maintainer then pointed out me us.  

We have [a PR pending](https://github.com/eddelbuettel/pinp/pull/79) that integrates it into [pinp](https://github.com/eddelbuettel/pinp), currently waiting on coauthor @coatless to review.

**Comment by eddelbuettel** [comment]
I spoke too soon. "Just" newer PNAS does not do the trick, we also need an older `titlesec`.  Investigation ongoing while stop-gap release made.
