### ISSUE TITLE
Could we replace with rmarkdown::pdf_document() with bookdown::pdf_document2() globally?

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rticles#243]
Currently, it seems like all rticles outputs rest upon `rmarkdown::pdf_document()` format.

However, would there be any way we could replace it with `bookdown::pdf_document2()` so that users can cross-reference sections? Furthermore, given that `bookdown::pdf_document2()` is inclusive of the basic `rmarkdown::pdf_document()`, what would be any expected conflict other than benefits?

I was attempting to add a new journal templat to `rticles` package using `bookdown::pdf_document2()` format; however, I have just found that `bookdown` is listed under `Suggests:` so I am in dillemma as to how to deal with this issue.

If you find switching `rmarkdown::pdf_document()` into `bookdown::pdf_document2()` unnecessary, would you mind adding `bookdown` to `Imports:` field?

**Comment by yihui** [comment]
All **rticles** output formats can be used as the "base format" for `bookdown::pdf_book`. There is an example at https://github.com/rstudio/rticles/issues/92#issuecomment-402784283
