### ISSUE TITLE
`rjournal_article()` cannot knit code tags containing "_"

### ISSUE THREAD

**Issue by phargarten2** [rstudio/rticles#248]
Thank you for allowing me to prepare articles using LaTeX without leaving R Studio environment. 

When knitting together my document using `rjournal_article()`, the document could not knit any `\code{}` segments that included underscores. I am doing so on a Mac, but it may not be problem on Windows. As you know, users frequently use the dollar sign to extract an element from a list or an underscore in an object's names.  For instance, typing the object `apple_orange` 

``` 
 \code{apple_orange} i
```
in the wording in a Rmarkdown file give the error: 
``` 
> ! Missing $ inserted.
<inserted text> 
                $
l.9 are saved in the \code{apple_orange}
```

[Finding this link]( https://stackoverflow.com/questions/2476831/getting-the-error-missing-inserted-in-latex),  the addition of the **underscore** LaTeX package in the `RJournal.sty` file seems to fix the problem.  

In case this happens to other users of **rticles**, could you consider adding this package to `RJournal.sty`?

Thanks!

**Comment by yihui** [comment]
I'm not sure when I'll have time to take a close look at this issue. I guess the best solution for now is probably to escape special characters such as `_` and `$` (i.e. add backslashes before them).

**Comment by phargarten2** [comment]
Here is a reproducible example. I created a new template using R Studio and added the line 
` Typing \code{apples_oranges} `
under **Introduction.**
[Using Underscores.zip](https://github.com/rstudio/rticles/files/3664606/Using.Underscores.zip)

**Comment by yihui** [comment]
Thanks! As I said, `\code{apples\_oranges}` is probably the best way to go for now.
