### ISSUE TITLE
Instructions for adding templates

### ISSUE THREAD

**Issue by mbarison** [rstudio/rticles#249]
Hi, thank you for this very nice package!

There is a template or two that I would like to add, are there any instructions on how to add new templates to the package?

Thanks!

**Comment by yihui** [comment]
You may take a look at the pull requests from other contributors (especially those that were merged): https://github.com/rstudio/rticles/pulls Thank you!

**Comment by cderv** [comment]
@mbarison you'll find some instructions in the PR template https://github.com/rstudio/rticles/blob/master/.github/PULL_REQUEST_TEMPLATE.md

and also you can now consult any previous PR for other templates easily as they are mentioned in the README
https://github.com/rstudio/rticles

**Comment by cderv** [comment]
@mbarison I also added some informations directly in the README so I think it is better documented now.
