### ISSUE TITLE
Plos template references

### ISSUE THREAD

**Issue by quentinmiagoux** [rstudio/rticles#250]
When knitting the Rmd file, I realised that the first reference was not tabbed, here is a preview directly from the basic template :

![Capture](https://user-images.githubusercontent.com/33721458/66662639-7e76e680-ec49-11e9-90c3-cec6cb7eda8d.PNG)

**Comment by yihui** [comment]
Cc relevant contributors @uvesten @BlackEdder @sjmgarnier to see if they have any ideas (https://github.com/rstudio/rticles/pulls?utf8=%E2%9C%93&q=is%3Apr+plos).

**Comment by BlackEdder** [comment]
I am not really sure what caused this. The plos template uses the plos.csl file from zotero. Maybe that one has been updated by now?

**Comment by cderv** [comment]
I looked a bit into that. I am not sure why this does not work. 
What I could say: 

* Currently the template use a csl file and `pandoc-citeproc` to include the bibliography. 
* The journal requirements are different (https://journals.plos.org/ploscompbiol/s/latex) and they do not provide a CSL file. Only a BST file and some process to add bibliography inside the tex file. 
* CSL file is helpful here but those included in https://editor.citationstyles.org/ does not seems to help. And I don't know why is does render correctly the first reference.

This will need someone using the PLOS template and willing to improve to chime in. Or a CSL expert :) 

In any case, we will happily review a PR.

**Comment by BlackEdder** [comment]
It might be worth testin it with another template (https://www.zotero.org/styles?q=plos)

**Comment by cderv** [comment]
Let's not that if we add `hanging-indent=true` in the plos.csl we get this 
![image](https://user-images.githubusercontent.com/6791940/90504602-9f557580-e151-11ea-9a83-319efdd795e9.png)

here 
https://github.com/rstudio/rticles/blob/7917d8b9f6297e3cf66b21561cf902b26895da58/inst/rmarkdown/templates/plos_article/skeleton/plos.csl#L295

to 
```xml
  <bibliography et-al-min="7" et-al-use-first="6" second-field-align="flush" hanging-indent="true">
```

I don't if this is missing for the csl plos file. @BlackEdder, is this something you can chack in the other template you provide ? 
I am not used to csl files

**Comment by BlackEdder** [comment]
I tried both the zotero template (see above) and the proposed fix, but it did not seem to make any difference.

**Comment by cderv** [comment]
I have updated plos skeleton to use the CSL from zotero. This way we'll have an updated CSL. 
https://github.com/rstudio/rticles/commit/034703260c7334ad1b05f7165a817e52f1b5819e

However, I don't know about the indent. It does not seem to be part of the CSL. I don't think this is something directly related to **rticles**. It is possibly something to fix in the CSL file. 

I'll close this as I don't know what we can do more.
