### ISSUE TITLE
Why do the templates not take the optional arguments of `pdf_document()`?

### ISSUE THREAD

**Issue by cboettig** [rstudio/rticles#26]
It seems that the current templates all define themselves without any of the arguments that are supported as arguments to the `pdf_document()`. (e.g. https://github.com/rstudio/rticles/blob/master/R/acm_article.R#L2) 

I'm not really clear on the reason for this. For instance, surely it would still be useful to be able to set a `fig.width` other than the default, or `keep_tex=TRUE` for an ACM article where the author will be submitting the tex file anyway? Or are these options somehow still available even though they are not function arguments to things like `acm_article()`?

**Comment by cboettig** [comment]
Ah, I see.  It seems that this requires more than just adding the arguments to the relevant function, as rmarkdown knows how to parse something like:

```
output_format: rtciles:elsevier
```

but not:

```
output_format:
  rtciles:elsevier: 
    keep_tex: true
```

even though either is valid for the standard output formats like `pdf_document`.  I suppose we should just be making sure to get the right defaults for all arguments hardwired in.

**Comment by mlist** [comment]
Does this mean it is not possible to add any additional arguments? What if I would like to use a specific markdown extension?

**Comment by yihui** [comment]
@mlist Which specific output format are you talking about? I guess we can certainly have a ... argument and pass it to `pdf_document` so that you can use, for example, a specific markdown extension.

**Comment by jjallaire** [comment]
The problem I have with ... on rticles functions is that because these are
custom templates many of the arguments won't actually work. If we do ...
then it may lead to frustration when things don't work as expected. So I'd
be in favor of explicitly adding md_extensions and whatever else is useful
rather than ...

**Comment by yihui** [comment]
Yeah that is also okay if md_extensions is the only extra thing @mlist wanted.

**Comment by mlist** [comment]
Yes, I was trying to add an md_extension. I see the point that allowing arbitrary stuff with ... could cause some frustration.

**Comment by yihui** [comment]
@mlist I guess this will be a relatively simple change, and you may try to submit a pull request to change the output format function that you are using.
