### ISSUE TITLE
`pandoc-crossref` will fail if these commented out

### ISSUE THREAD

**Issue by sunt05** [rstudio/rticles#273]
Just discovered your great work!
HUGE THANKS!!!

One issue identified if using pandoc with `pandoc-crossref`:
https://github.com/rstudio/rticles/blob/3445b4692a09ee1e8a5b000fc15793794cc0bf87/inst/rmarkdown/templates/copernicus_article/resources/template.tex#L84-L86

If these lines are commented out, then the headers by `pandoc-crossref` won't be correctly inserted.

**Comment by yihui** [comment]
There is a comment on the previous line:
https://github.com/rstudio/rticles/blob/3445b4692a09ee1e8a5b000fc15793794cc0bf87/inst/rmarkdown/templates/copernicus_article/resources/template.tex#L83-L86

Cc the template author @nuest (#172). I'm not the expert here.

**Comment by nuest** [comment]
Copernicus discourages adding any additional packages, see https://publications.copernicus.org/for_authors/manuscript_preparation.html

![image](https://user-images.githubusercontent.com/1325054/79952499-d1dcb380-847a-11ea-81fd-4ebad3d78d10.png)

IIRC correctly that is why is disabled that option for authors, however, I was not aware that the `pandoc-crossref` filter would be impacted by that.

@sunt05 Can you please provide a reproducible example so I can take a closer look? Thanks!

**Comment by cderv** [comment]
@sunt05 friendly ping here 😄 
Can you provide a reproducible example for @nuest  ?

**Comment by sunt05** [comment]
Sorry about the delay: as it's been a while since I tested the templated, I needed a bit longer to re-pick this up.
Now please test the template with files in this repo:
https://github.com/sunt05/test-r-template

### issue
if the above mentioned lines are commented out as instructed by Copernicus, the following issue would appear:
```
Error producing PDF.
! You can't use `\spacefactor' in vertical mode.
\@->\spacefactor 
                 \@m {}
l.77 \@
```

**Comment by cderv** [comment]
It seems you are not using `rticles` and `rmarkdown` R 📦  to render your document. Is it just for the example or are you always using template this way ? 
 
I believe the tex template are best used with those 2 packages package: `rmarkdown::render()` function and `rticles::copernicus_article()` format .

**Comment by sunt05** [comment]
> It seems you are not using `rticles` and `rmarkdown` R 📦 to render your document. Is it just for the example or are you always using template this way ?

I'm always using it this way: i.e., with pandoc, as I found the templates could be easily adapted for broader applicability with more generic markdown-based tools, e.g., `pandoc`


> I believe the tex template are best used with those 2 packages package: `rmarkdown::render()` function and `rticles::copernicus_article()` format .

Sorry that if this issue looks off-topic: please feel free to close it.

**Comment by cderv** [comment]
> I'm always using it this way: i.e., with pandoc, as I found the templates could be easily adapted for broader applicability with more generic markdown-based tools, e.g., pandoc

You may already know but **rmarkdown** also use pandoc for conversion. 

I believe the issue you get if from converting directly using the template. I did not identify why yet but I don't get the same tex file after pandoc conversion  from the command line or using `rmarkdown::render`. That means some things is happening when using Rmarkdown that you need to reproduce using pandoc;

**Comment by sunt05** [comment]
> I believe the issue you get if from converting directly using the template. I did not identify why yet but I don't get the same tex file after pandoc conversion from the command line ...

Did you use the following line to reproduce the error?
```
pandoc -f markdown+tex_math_single_backslash -o Manuscript.pdf --pdf-engine=pdflatex --template=template.tex --filter=pandoc-crossref test.md
```
Please note the `template.tex` file is a modified version, which can successfully produce a PDF.

I just update the repo with more description to reproduce the error as mentioned above:
```
pandoc -f markdown+tex_math_single_backslash -o Manuscript.pdf --pdf-engine=pdflatex --template=template_orig.tex --filter=pandoc-crossref test.md
```

Sorry about any confusion I might have brought up.

**Comment by cderv** [comment]
I can reproduce using your command. But I cannot reproduce if I use **rmarkdown** and **rticles** directly.
and I believe this comes from `pandoc-crossref` that you are using. 

`pandoc-crossref` is doing some stuff with the header-includes part, see https://github.com/lierdakil/pandoc-crossref/blob/master/lib/Text/Pandoc/CrossRef/Util/ModifyMeta.hs

So I don't think it likes this template that have this part commented. This is a compatibility issue with `pandoc-crossref` I believe. 

Best thing to do  here is to use your own template I think

**Comment by sunt05** [comment]
Thanks for the discussion and help! @cderv 

I'll use the templates more *wisely* with `pandoc-crossref` 😃
