### ISSUE TITLE
Ctex template Keywords

### ISSUE THREAD

**Issue by byronwwang** [rstudio/rticles#275]
Hi,

Is there any possible to support keywords setting in the rticles:Ctex template like others did?

It's would be grateful.

**Comment by yihui** [comment]
Sorry, but I don't have time for this task. Either you, or someone else (e.g. @XiangyunHuang) has to send a PR. Thanks!

**Comment by XiangyunHuang** [comment]
@yihui @byronwwang 我不建议对 ctex 模版进行功能扩充，应该引导用户更多地使用 Pandoc 内建的模版，内建的模版其实已经覆盖咱们的 ctex 模版了，咱们的模版存在的意义在消失，它的历史使命已经完成。

**Comment by XiangyunHuang** [comment]
仅提供一个例子 https://github.com/XiangyunHuang/masr/blob/master/examples/pdf-document.Rmd
输出 https://masr.netlify.app/pdf-document.pdf

**Comment by yihui** [comment]
@XiangyunHuang 我同意啊。要是现在 Pandoc 内置模板现在可以用 ctex 文档类了，那我们就该换到内置模板上。从你的例子来看，rticles 里面的这个 ctex 模板可以删了？https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/ctex/resources/template.tex 如果能删就太好了，我也不想维护它。

那 Pandoc 内置模板支持使用关键词吗？

**Comment by XiangyunHuang** [comment]
@yihui 都是支持的，我上面给的例子里还包含了主题 subject 

https://github.com/XiangyunHuang/masr/blob/master/examples/pdf-document.Rmd#L31-L34

**Comment by yihui** [comment]
好，你有空把这个包的模板删了、把示例文件（`skeleton.Rmd`）相应更新一下吗？谢谢！

**Comment by XiangyunHuang** [comment]
@yihui PR 已经在路上

**Comment by yihui** [comment]
@byronwwang Keywords are supported now: https://github.com/rstudio/rticles/blob/23ecb218be632001c25ae56c6e7d2d30ec14c195/inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd#L8-L10

If you are not satisfied by the support, you can provide your own LaTeX template. The default template is from Pandoc: https://github.com/jgm/pandoc/blob/master/data/templates/default.latex
