### ISSUE TITLE
Default tufte book fails in current RStudio Preview under Ubuntu 14.10

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rticles#28]
At the end of knitting (having installed the required packages), I get

```
/usr/lib/rstudio-server/bin/pandoc/pandoc Test_Tufte_Book.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Test_Tufte_Book.tex --filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc --table-of-contents --toc-depth 3 --template /usr/local/lib/R/site-library/rticles/rmarkdown/templates/tufte_ebook/resources/tufte-ebook.tex --number-sections --highlight-style pygments --latex-engine xelatex --bibliography knitcitations.bib 
Writing 9 Bibtex entries ... OK
Results written to file 'knitcitations.bib'
output file: Test_Tufte_Book.knit.md

pandoc-citeproc: could not find locale data for C-UTF-8
pandoc: Error running filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc
Error: pandoc document conversion failed with error 83
Execution halted
```

Ubuntu 14.10, current, RStudio Server Version 0.99.315

**Comment by eddelbuettel** [comment]
For what it is worth it works with RStudio (Desktop) Version 0.99.292 on Ubuntu 14.10 32bit, also current.

**Comment by cboettig** [comment]
Hey Dirk,

This is the same issue as:
https://github.com/rstudio/rmarkdown/issues/383#issuecomment-76521681

Seems rmarkdown is deciding to change to the C.UTF-8 locale for some
reason, which we haven't configured on rocker, but I haven't had a chance
to dig further

**Comment by eddelbuettel** [comment]
And it also works in RStudio (Desktop) Version 0.99.315 on the same Ubuntu 14.10 64, current, server where RStudio Server 0.99.315 failed -- so it is a matter of setting the environment variable when it is missing as it appears to be for the server process.

**Comment by eddelbuettel** [comment]
Hi Carl -- this actually was not Rocker related.  I run my RServers 'straight up' on Ubuntu.

**Comment by jjallaire** [comment]
Sounds like I should be able to repro this on a stock Ubuntu 14.10 box --
I'll spin one up and hopefully see the same behavior. My guess is that this
is related to:

(a) Some change in the new pandoc-citeproc that requires/interacts with
locale environment variables differently; and

(b) The fact that RStudio Server does some over-aggressive environment
variable filtering that is probably masking the (newly) required variables.

Stay tune and I'll hopefully have this sorted out soon....


On Sat, Feb 28, 2015 at 2:47 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
If it helps, here is what `system("env")` sees. There is an LC_CTYPE already set in a value different from the one the error showed.  Odd.

```
R> system("env")
R_UNZIPCMD=/usr/bin/unzip
USER=edd
GIT_ASKPASS=rpostback-askpass
LD_LIBRARY_PATH=/usr/lib/R/lib:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server
HOME=/home/edd
R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
R_BROWSER=xdg-open
PAGER=/usr/bin/pager
LC_CTYPE=en_US.UTF-8
R_SYSTEM_ABI=linux,gcc,gxx,gfortran,?
SSH_ASKPASS=rpostback-askpass
RSTUDIO_HTTP_REFERER=http://max:8787/
LOGNAME=edd
TAR=/bin/tar
R_LIBS_USER=
RMARKDOWN_MATHJAX_PATH=/usr/lib/rstudio-server/resources/mathjax-23
RSTUDIO_PANDOC=/usr/lib/rstudio-server/bin/pandoc
R_PAPERSIZE_USER=letter
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
R_BZIPCMD=/bin/bzip2
R_INCLUDE_DIR=/usr/share/R/include
R_SESSION_TMPDIR=/tmp/RtmpRDpvbF
DISPLAY=:0
R_GZIPCMD=/bin/gzip
LN_S=ln -s
SED=/bin/sed
R_PDFVIEWER=/usr/bin/xdg-open
RSTUDIO_USER_IDENTITY=edd
R_TEXI2DVICMD=/usr/bin/texi2dvi
R_HOME=/usr/lib/R
R_PRINTCMD=/usr/bin/lpr
R_DOC_DIR=/usr/share/R/doc
R_SHARE_DIR=/usr/share/R/share
RSTUDIO=1
R_ZIPCMD=/usr/bin/zip
PWD=/home/edd
R_PLATFORM=x86_64-pc-linux-gnu
R_PAPERSIZE=letter
RS_RPOSTBACK_PATH=/usr/lib/rstudio-server/bin/rpostback
MAKE=make
R_RD4PDF=times,inconsolata,hyper
EDITOR=vi
R> 
```

**Comment by cboettig** [comment]
@eddelbuettel Can you try setting `LANG==en_US.UTF-8` (or `Sys.setenv(LANG, "=en_US.UTF-8")`) and see if that fixes it? It did for me in https://github.com/rstudio/rmarkdown/issues/383

**Comment by eddelbuettel** [comment]
Where?  Via `Sys.putenv()` once running?  I don't start this background server process myself...

**Comment by eddelbuettel** [comment]
Yes, after

```{.r}
Sys.setenv(LANG="en_US.UTF-8")
```

compilation works.  So the hunch by JJ about excessive pruning of env vars seems prescient.

(The previewer comes up with an empty file though...)

**Comment by eddelbuettel** [comment]
A little bird told me this was indeed an issue on the RStudio Server side, which has been addressed there -- so I am closing this.
