### ISSUE TITLE
rticles::springer_article latin names not in italics

### ISSUE THREAD

**Issue by hnguyen19** [rstudio/rticles#281]
Hello,

All the Latin names (Amaranthus rudis and Amaranthus spp.) in my references are not in italics. Please advise how to fix that. Thank you.
[art_test2.pdf](https://github.com/rstudio/rticles/files/4339831/art_test2.pdf)

```
xfun::session_info('rticles')
R version 3.6.2 (2019-12-12)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 14393), RStudio 1.2.5033

Locale:
  LC_COLLATE=English_United States.1252 
  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 digest_0.6.25  
  evaluate_0.14   glue_1.3.1     
  graphics_3.6.2  grDevices_3.6.2
  highr_0.8       htmltools_0.4.0
  jsonlite_1.6.1  knitr_1.28     
  magrittr_1.5    markdown_1.1   
  methods_3.6.2   mime_0.9       
  Rcpp_1.0.3      rlang_0.4.4    
  rmarkdown_2.1   rticles_0.14   
  stats_3.6.2     stringi_1.4.6  
  stringr_1.4.0   tinytex_0.20   
  tools_3.6.2     utils_3.6.2    
  xfun_0.12       yaml_2.2.1 
```

**Comment by cderv** [comment]
Can you provide a reproducible example of what you expect ? 

`rticles` contains the template for Springer with the three bibstyle available: spbasic(default), spphys, spmpsci, as shown in Rmd template and depending on the article you write I guess (I am not a Springer expert here) Which one do you need ? 

I guess you can provide a custom `.bst` file if you want... 

Hope it helps

**Comment by hnguyen19** [comment]
Thanks for your feedback. Per the bst files, I should use `spbasic` because it handles life sciences articles. I haven't found any lines in spbasic.bst that allows me to specify organism latin names to be in italics. Please see the first citation in the References section from the attached paper with italicized latin names. That's what I expect. 
[Salazar2020_Article_DillapioleInPiperHoltoniiAsAnI.pdf](https://github.com/rstudio/rticles/files/4344615/Salazar2020_Article_DillapioleInPiperHoltoniiAsAnI.pdf)

**Comment by cderv** [comment]
🤔 In fact I am not sure to understand correct your issue. 
Did you just try to put in italic the text in you `bibliography.bib` file ? 
Doing a little search, this is with `\textit{}`. 
So using ike `Title = {This is a \textit{text to italicized} in this sentence.}`

In the template project of `springer_article()` it works.

Is this what you are looking for ? Should it be different in the journal template you need ?

**Comment by hnguyen19** [comment]
Thank you for pointing out the source of the problem. \textit{} solves the italics problem but it makes the whole entry displayed improperly (I will report in another post).

 The BibTex export from Google Scholar gave me the following, with no indication of italics for the Latin names.
@article{butts2016management,
  title={Management of pigweed (Amaranthus spp.) in glufosinate-resistant soybean in the Midwest and Mid-South},
  author={Butts, Thomas R and Norsworthy, Jason K and Kruger, Greg R and Sandell, Lowell D and Young, Bryan G and Steckel, Lawrence E and Loux, Mark M and Bradley, Kevin W and Conley, Shawn P and Stoltenberg, David E and others},
  journal={Weed technology},
  volume={30},
  number={2},
  pages={355--365},
  year={2016},
  publisher={Cambridge University Press}
}
This happens to a lot of my references that involve a Latin name. So, to solve my italics problem, I will have to manually change all the Latin names to \textit{Latin names}. I don't mind doing that for my paper but this seems to be a systematic error that makes everyone who want to cite that same paper to have to change their .bib file on their own. I wish I could change that on my file and everyone else who need that entry can just use the properly displayed one.

**Comment by cderv** [comment]
At the end, I am not sure there is bug to fix in `rticle` somewhere. It is just a matter of formatting and latex / bibfile expertise. 

Following [the issue guide](https://yihui.org/issue/#got-a-question), this is more like a question and you could ask on SO, RStudio community or a community around Life science I guess, to get the attention of others - there could be someone with experience on this. If you link it back here, I'll be happy to keep following and help as I can.

I never wrote a paper for life science so I don't the best pratices and tricks. If you found something that should be improved in rticles, you'll can share it back here.

Don't you think ?

**Comment by jcolomb** [comment]
It is a known problem  of the whole scholarly communication system, italics information are not sent to crossref or exported to bibtex/RIS.

My advice is to deal with that at the proofreading stage and not care before the article is accepted.

**Comment by cderv** [comment]
I don't think we'll do more on this one and we'll follow @jcolomb advice: this should be taking care of at the proofreading step.
