### ISSUE TITLE
rticles output in *.docx format

### ISSUE THREAD

**Issue by gtalckmin** [rstudio/rticles#283]
Hello,

Is there a way to output a rticles Journal formatted file? I am happy with the PDF but my supervisors/reviewers are requesting *docx format.

I tried this, but it does not work.

output: 
  bookdown::word_document2:
    base_format: rticles::springer_article
    number_sections: no

**Comment by gtalckmin** [comment]
13.4 LaTeX content
As the only output format of the rticles formats is PDF
https://bookdown.org/yihui/rmarkdown/rticles-latex.html

**Comment by VEZY** [comment]
I know this issue is closed, but you can still output docx documents (if you didn't put LaTeX in the doc though) by modifying the output such as:
```YAML
output: 
  rticles::springer_article: default
  word_document: default
```
NB: you can do it for any format, e.g. HTML. 
You can also use Pandoc with a custom template for your word. 

Another solution is to open your PDF using word, and to save the document as docx. This works perfectly.

**Comment by gtalckmin** [comment]
Salut @VEZY, 
Thanks for your reply. 
I am aware I could output to a doc file by using a standard template. However, I am unaware that it is possible using the rticles "template". It would be great though. 

Until now, my best solution, as you mentioned, was exporting from PDF to docx. However, whenever I tried to export a PDF as a word document, most times, the Fonts were not correct.
 
The best option, in my experience, is to export the document *without* any Figures. Otherwise, the whole page layout is compromised. fonts are mixed etc. 
Thanks for your input. Cheers

**Comment by alapo** [comment]
This same comment was brought up on the officedown GitHub. I am attempting to get this working using that package. You can view my post [here](https://github.com/davidgohel/officedown/issues/44)
