### ISSUE TITLE
JSS template: Appendix not possible after references

### ISSUE THREAD

**Issue by mbannert** [rstudio/rticles#29]
Whenever I try to place a chapter after the references, the references are not displayed. Though the JSS (as most journals I know) have the appendix in the very back. Is there a way to cure this? So far, I only saw modifying the .tex and rendering it again, but I suppose this generates other troubles, plus it is against RR.

**Comment by krlmlr** [comment]
References:

https://github.com/jgm/pandoc/issues/771

http://stackoverflow.com/questions/16427637/pandoc-insert-appendix-after-bibliography

**Comment by yihui** [comment]
With newer versions of Pandoc, I think the ideal solution is `<div id="refs"></div>` as mentioned in https://stackoverflow.com/a/44294306/559676.
