### ISSUE TITLE
The PLoS template is now out of date (I think)

### ISSUE THREAD

**Issue by brendan-r** [rstudio/rticles#30]
It changed in January 2015, there's some notes on it [here](http://www.ploscompbiol.org/static/latexGuidelines), and the .tex file and associated bits are [here](http://www.ploscompbiol.org/static/plos_template.zip).

The example .pdf they provide looks very different to what the example produces. Looking at the timeline for commits, I'm guessing that `rticles` is now out of date. Here's the new look:

![newplos](https://cloud.githubusercontent.com/assets/3510374/7152791/9f480616-e2f6-11e4-893b-f4b08d1882a0.png)

I'd offer a pull request, only I have no idea what that might entail! Apologies.

**Comment by jjallaire** [comment]
@sjmgarnier Would you be willing to update the PLoS template based on these changes?

**Comment by sjmgarnier** [comment]
@jjallaire I'm traveling for the next week or so. I'll try to get to it when I'm back home.

**Comment by jjallaire** [comment]
Great, thanks!

**Comment by helmingstay** [comment]
Any word on this?

**Comment by sjmgarnier** [comment]
@helmingstay I tried but there were significant changes between the old and new formats, and that would have required a little more time than what I can dedicate to this. Feel free to give it a try.

**Comment by yihui** [comment]
We will be waiting for a PR to update this particular template. Thanks!
