### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#303]
Currently build is failling https://travis-ci.org/github/rstudio/rticles/builds/714523391

It seems like it is taking too long, so travis things it fails. Maybe because of all the tex package to install. 🤔

**Comment by yihui** [comment]
I guess I'm more familiar with the TeX Live stuff, so let me try to fix this issue first. If I can't figure it out, I'll leave it to you. Thanks!

**Comment by yihui** [comment]
Fixed now: https://travis-ci.org/github/rstudio/rticles/builds/714523391

In case it should become a problem in the future again, we can preinstall some LaTeX packages to avoid the timeout (the time is spent on looking for missing packages and installing them):

```yaml
  - tlmgr install achemso ametsoc babel-french biblatex carlisle chemgreek crop dblfloatfix draftwatermark endfloat endnotes epsf esvect etex-pkg everypage floatflt forarray hyphen-french hyphenat jknapltx logreq marginnote mhchem mnras moreverb pdfsync psfrag rsfs seqsplit sidecap soul soulutf8 stix tabto-ltx tex-gyre totcount xypic
  - tlmgr path add
```

**Comment by cderv** [comment]
This is now working. It could have been a travis issue. @yihui if you've done anything, please share.

**Comment by cderv** [comment]
Awesome thank you.
