### ISSUE TITLE
JSS continuation prompt when eval=FALSE

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#311]
Following #254  comment,  the continuation prompt should be `+` for code chunk, evaluated or not. 
That means
````md
```{r}
f <- function(a, b) mean(c(a,b))
f(a = 1,
  b = 2)
```
or 

```{r, eval = FALSE}
f <- function(a, b) mean(c(a,b))
f(a = 1,
  b = 2)
```
````

shoult be rendered as this in both case
```
R> f <- function(a, b) mean(c(a,b))
R> f(a = 1,
+   b = 2)
```

Currently, it is not the case. #294 fixed part of the issue in rticles by changing `R+` to `+` but this works only for evaluated chunks. 

In fact, the transformation is based on a hook
https://github.com/rstudio/rticles/blob/ec5e82b21c89ecb2d62ea935b1a3104fd0e48375/R/jss_article.R#L46-L53
but for `eval=FALSE` , chunk input is not parsed the same as when `eval=TRUE` so the hook does not apply the same. 
It could be a bug elsewhere than rticles...

**Comment by yihui** [comment]
Originally I thought it was a **knitr** bug. With the example below, however, I guess it is a problem specific to `jss_article()`:

````
---
title: "Prompts"
---

```{r}
knitr::opts_chunk$set(prompt = TRUE)
```


```{r}
f <- function(a, b) mean(c(a,b))
f(a = 1,
  b = 2)
```

```{r, eval = FALSE}
f <- function(a, b) mean(c(a,b))
f(a = 1,
  b = 2)
```
````

I'll leave it to you to investigate.

**Comment by yihui** [comment]
When `eval=FALSE`, you'll need to split the code into complete expressions, and add prompts to each expression. Here is what I did in **knitr**: https://github.com/yihui/knitr/blob/cb796995ffac0a1fc1a81648151b6fde2e0bcdf8/R/highlight.R#L19-L23

It used an internal function in **highr**, and I'll try to move and export it in **xfun** so you can call it.

**Comment by cderv** [comment]
Yes this fixes it. It is odd that we must rewrite this prompt stuff in the `jss_article` format and not be able to use **knitr** stuff or **highr** stuff. I would have expect we could manage this by setting `options(prompt = "R> ")` and use default `getOption('continue')` which is `+`

I am not enough familiar with this `jss_article` function and why we need for example `out_format = sweave`. it is working so we'll just make the fix for now. 

Note: We may need also to export the `one_string` function currently in `rmarkdown` or `knitr`. I could easily add it in utils.R but it seems that having it in one place it better.

**Comment by yihui** [comment]
> I am not enough familiar with this `jss_article` function and why we need for example `out_format = sweave`

The code was mainly copied from https://github.com/yihui/knitr/blob/cb796995ffac0a1fc1a81648151b6fde2e0bcdf8/R/hooks-latex.R#L300-L319

> It is odd that we must rewrite this prompt stuff in the `jss_article` format and not be able to use **knitr** stuff or **highr** stuff. I would have expect we could manage this by setting `options(prompt = "R> ")` and use default `getOption('continue')` which is `+`

Yes, I agree with you. We should reuse **knitr** output hooks instead of providing new hook functions in this package. Currently there is a small problem that makes it inconvenient to reuse the hooks, though. I've opened https://github.com/yihui/knitr/issues/1885 and it can be a good first issue for you when you start working on **knitr**.
