### ISSUE TITLE
Rename template folders to shortten the path

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#315]
See discussion in https://github.com/rstudio/rticles/pull/297#issuecomment-675489389

One solution is to remove the `_article` part in template folder 
```
$ ls inst/rmarkdown/templates/
acm_article  arxiv_article           elsevier_article   mnras_article     rsos_article
acs_article  asa_article             frontiers_article  oup_article       rss_article
aea_article  bioinformatics_article  ieee_article       peerj_article     sage_article
agu_article  biometrics_article      joss_article       plos_article      sim_article
amq_article  copernicus_article      jss_article        pnas_article      springer_article
ams_article  ctex                    mdpi_article       rjournal_article  tf_article
```

That would require to modify each format function accordingly: This folder name is used to find the resource in `pdf_document_format()` and currently match the format name. 

## To Do 
- [x] Rename the folders
- [x] Update the format functions
- [x] Update the PR template

**Comment by yihui** [comment]
Also remember to update https://github.com/rstudio/rticles/blob/master/.github/PULL_REQUEST_TEMPLATE.md
