### ISSUE TITLE
Miscellaneous Issues

### ISSUE THREAD

**Issue by znmeb** [rstudio/rticles#32]
1. 'DESCRIPTION' file still has skeleton data for Title, Author, Maintainer, etc.
2. Trying to knit "tufte_ebook" template crashes because "papeR" is no longer in CRAN.
3. Building from the tufte_ebook requires xelatex and a few texlive (on Linux) packages that aren't installed by default. I haven't tried this on Windows with MikTeX.

**Comment by znmeb** [comment]
TeXLive packages needed (on Fedora Linux):

```
texlive-xetex
texlive-hardwrap
texlive-xltxtra
texlive-euenc
texlive-xetex-def
```

**Comment by jjallaire** [comment]
@justsomeone1001 Could we update the tufte_ebook template to not require the *papeR* package (which apparently is no longer on CRAN).

**Comment by justsomeone1001** [comment]
I'll take care of it

**Comment by jjallaire** [comment]
Thanks!

J.J.
