### ISSUE TITLE
Location of references in sim 

### ISSUE THREAD

**Issue by CarolineXGao** [rstudio/rticles#338]
Hi 

 I am trying to use this command to manually specify the location of references.

`<div id="refs"></div>`

It seems to be working with a few journal styles but not for sim.  The references were always displayed at the end of the document. This is tested using sim skeleton.Rmd file.  Is there anything that I can do to fix this?

Thanks very much!! 

Best, 

Caroline

**Comment by cderv** [comment]
> I am trying to use this command to manually specify the location of references.
> `<div id="refs"></div>`

`sim_article` is using by default `natbib` as a citation package and the feature you are trying to use is from _pandoc-citeproc_. So by default it would not work. The journal that works may be those which use pandoc citeproc by default.

Did you try with the default `citation_package` argument, or did you correctly changed it ?

**Comment by CarolineXGao** [comment]
Thanks very much. Now I know where went wrong. Will try citation_package see if it works 
Much appreciated : )
