### ISSUE TITLE
templates for other journals?

### ISSUE THREAD

**Issue by ajbass** [rstudio/rticles#35]
Awesome package- I was wondering if anyone was working on templates for computational biology journals (i.e Bioinformatics)?

Thanks!

**Comment by jbkunst** [comment]
Or Journal of Econometrics http://terpconnect.umd.edu/~yuanliao/risk/risk.pdf.

Thanks for this package!
Bests!

**Comment by ajbass** [comment]
are there any plans to update this package with new journal templates? I think fields where Rstudio is used heavily will benefit. Journals such as bioinformatics, biostatistics, nature, science, etc.

**Comment by hlszlaszlo** [comment]
Very nice package! Keep on the good work.

**Comment by winni2k** [comment]
@ajbass: it looks like pull requests are accepted... https://github.com/rstudio/rticles/issues/107#issue-213139239

**Comment by yihui** [comment]
We don't actively write journal papers, and we are not LaTeX experts. Please feel free to contribute more templates. Most templates in this package are contributed by other authors. Thanks!
