### ISSUE TITLE
Ctex template Chinese character overlaps

### ISSUE THREAD

**Issue by ray1919** [rstudio/rticles#357]
I write Chinese rmd report using Ctex template. Some Chinese character will overlap as one character like"分布", ”部分". I don't know how to solve this problem. Thank you for your time

**Comment by cderv** [comment]
@ray1919 Sorry for the delay, is this still an issue ? 

For question, Q&A website are generally more appropriate to have a quick answer
https://yihui.org/issue/#got-a-question
