### ISSUE TITLE
cls files not found when using jss format

### ISSUE THREAD

**Issue by cc20002002** [rstudio/rticles#376]
Hi,

I have the following minimal example that cannot be compiled into pdf. It turns out it can produce tex files but not a pdf. Reason being tex cannot find jss file:

File `jss.cls' not found.

So do I have to manually download abd put jss.cls into the same folder of my rmarkdown file?

Cheers,
```
---
title: "***"
documentclass: jss
output: rticles::jss_article
author:
- name: C1233
  affiliation: 123123
header-includes:
    - \usepackage{booktabs}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = "formatR",
                      tidy.opts = list(blank = FALSE, width.cutoff = 40),
                      echo = F,
                      results = "markup")
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
```

texttext
```

**Comment by cc20002002** [comment]
OK. So if I use rstudio to create a jss template it will give me a cls file. Please close the issue.

**Comment by cderv** [comment]
Yes the assets are contained as template inside the package and copied to the user system when you create a template. 
You can do that using RStudio, but also at the command line: 
```r
rmarkdown::draft("MyJSSArticle.Rmd", template = "jss", package = "rticles")
```

See documentation in https://bookdown.org/yihui/rmarkdown/rticles-start.html
