### ISSUE TITLE
Issue with Pandoc CSL refs and some articles templates

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#383]
Reported first in tinytex https://github.com/yihui/tinytex/issues/298

````r
> dir.create(tmp_dir <- tempfile())
> owd <- setwd(tmp_dir)
> rmarkdown::draft("myArticle", template = "frontiers", package = "rticles", edit = FALSE)
> list.files("myArticle/")
> setwd("myArticle/")
> rmarkdown::render("myArticle.Rmd", quiet = TRUE)
! You can't use `\vadjust' in vertical mode.
l.300 \leavevmode\vadjust
                          pre{\hypertarget{ref-Neurobot2013}{}}% 

Error: LaTeX failed to compile myArticle.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See myArticle.log for more info.
> setwd(owd)
> unlink(tmp_dir, recursive = TRUE)
````

Error seems to be from Pandocs CSL references part
````
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-Neurobot2013}{}}%
Author4, N., and Author5, N. (2013). Title of the article.
\emph{Frontiers in Neurorobotics} 7.
doi:\href{https://doi.org/10.3389/fnbot.2013.56789}{10.3389/fnbot.2013.56789}.

\leavevmode\vadjust pre{\hypertarget{ref-Neuro2013}{}}%
LastName1, A., LastName2, A., and LastName2, A. (2013). Article title.
\emph{Frontiers in Neuroscience} 30, 10127--10134.
doi:\href{https://doi.org/10.3389/fnins.2013.12345}{10.3389/fnins.2013.12345}.

\leavevmode\vadjust pre{\hypertarget{ref-Gene2012}{}}%
OtherAuthor, N., and Coauthor, N. S. (2012). Article title.
\emph{Frontiers in Genetics} 30, 16417--16418.
doi:\href{https://doi.org/10.3389/fgene.2012.54321}{10.3389/fgene.2012.54321}.

\end{CSLReferences}
````

Same with `elsevier` template
```r
rmarkdown::draft("myArticle", template = "elsevier", package = "rticles", edit = FALSE)
```

**Comment by cderv** [comment]
It seems new from Pandoc 2.13 as with previous version is work ok. (tested locally with 2.13 then 2.11.4)

I added a test for Pandoc devel to confirm:

* Fail with last night version: https://github.com/rstudio/rticles/runs/2322462463?check_suite_focus=true
* Works with Pandoc 2.11.4: https://github.com/rstudio/rticles/runs/2322462437?check_suite_focus=true

**Comment by IndrajeetPatil** [comment]
Does this fix the issue mentioned here? 
https://stackoverflow.com/questions/67004645/r-knitting-error-rticles-vadjust-in-vertical-mode

**Comment by cderv** [comment]
Possible. Did you try with dev version of **rticles** ? 

Do not hesitate to open a new issue also if something seems wrong

**Comment by cderv** [comment]
I just checked and tested: yes #390 should have fixed your issue reported in SO. Frontier article compile without issue. 

When you encountered such issue, do not hesitate to try dev version. 

```r
remotes::install_github("rstudio/rticles")
```

**Comment by IndrajeetPatil** [comment]
Thanks for the quick response, Christophe! I can confirm that the GitHub version indeed solves this problem.
