### ISSUE TITLE
resolve conflict between lipic format and bookdown regarding environment 

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#392]
This follows https://github.com/rstudio/rticles/pull/288#issuecomment-721232934 and https://github.com/rstudio/bookdown/issues/1001

and the new option in dev **bookdown** : `bookdown.theroem.preamble`

We need to set that to FALSE for some formats where there is a conflict and document

cc @nuest

**Comment by nuest** [comment]
Thanks for the ping @cderv. So, I'm trying to remember what was the problem here :-)

With `bookdown.theorem.preamble` set to `FALSE`, can we switch back to the syntax that was reverted in https://github.com/rstudio/rticles/pull/288/commits/75ea637d0d8be5bdfefb064190faad31437e61f6 ?

**Comment by cderv** [comment]
Yes exactly (or almost if we look at the syntax)

If we set this option to false, this should avoid the conflict of two definition of the environment. This means the syntax supported by bookdown could be used with `bookdown::pdf_book` 

````markdown
::: {.theorem #testenv-theorem}
Fusce eu leo nisi. Cras eget orci neque, eleifend dapibus felis. Duis et leo dui. Nam vulputate,   velit et laoreet porttitor, quam arcu facilisis dui, sed malesuada risus massa sit amet neque.
:::
````

I did not try yet with LIPIC format though

**Comment by cderv** [comment]
@nuest I add the option in the skeleton to show it can be used to deactivate the environment conflict.

**Comment by nuest** [comment]
Nice!

That means we could switch to the new syntax for theorems, right?

**Comment by cderv** [comment]
Yes you should be able to. Tell me if it is not working for some reason
