### ISSUE TITLE
R file produced by `rjournal_article` is not replaced by new one

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#394]
We forgot to set `overwrite = FALSE` here I think: 
https://github.com/rstudio/rticles/blob/84a8fb4d705990cf455ff8cb1e0c8340d04bda0a/R/rjournal_article.R#L94

Meaning that the new purled R file was not copied to the output dir unless the previous one was cleaned. No error or warning issued with `file.copy` in this case... 

That is nasty bug I think. But with an easy fix

Thanks @apreshill for finding this

**Comment by Enchufa2** [comment]
I suppose this is a feature to automatically generate the replication script from the Rmd. But I always maintain a separate `filename.R` replication script, and now it gets overwritten after this change. Is there an option to switch off this feature?

**Comment by Enchufa2** [comment]
I see no way to switch this off. And given that previously it was possible to maintain a custom replication script, I consider this a regression. A proper fix would be to add some comment to the generated file (like "this was automatically generated, do not edit by hand"), and only overwrite it if such comment is present.

**Comment by cderv** [comment]
Hi @Enchufa2 ! 

Thanks for the report. This is indeed something we did not think through.

We could also provide an argument in the function to opt-out this: 
````yaml
output: 
  rjournal_article: 
    purl: false
```

I like your suggestion though with the special comment in the script. 

I'll open an issue to track your report specifically.

**Comment by Enchufa2** [comment]
Nice, thanks!
