### ISSUE TITLE
Update LaTeX templates 

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#410]
Pandoc 2.14 has updated its tex template. https://pandoc.org/releases.html

We should have a look to see what may need to be modified in our templates

**Comment by mfhepp** [comment]
Three ideas:

1. Check if the diff of a new Pandoc releases is relevant semi-automatically for all templates.
2. Add test cases, i.e. check if existing templates yield the same, expected output with a new Pandoc release (this would spot changes in variables passed from Pandoc to the template etc.).
3. Modularize, like [Quarto is doing](https://quarto.org/docs/journals/). Basically, they seem to break down each new Pandoc LaTeX template into what they call partials (sub-templates) and compile the entire template by importing those.

See also [the GitHub repository](https://github.com/quarto-journals/) and [instructions for new formats](https://github.com/quarto-journals/article-format-template).

This allows replacing just e.g. the [TeX code for tables](https://github.com/quarto-journals/article-format-template/blob/main/_extensions/aft/partials/tables.tex). The basic mechanism is that Quarto uses the default "partial" to assemble the complete template, unless a format includes a modified partial.

The advantage of this is that the individual adjustments become much more independent from the evolution of the Pandoc template as a whole.

The downside is that you may need to tweak RStudio to implement the mechanism (but that sounds not too difficult).

**Comment by mfhepp** [comment]
Addendum: The [history of the `template.latex` file of Pandoc is here](https://github.com/jgm/pandoc/commits/master/data/templates/default.latex)

**Comment by cderv** [comment]
Some updates has been done. Ideas for improvement has been moved to new issue to track
