### ISSUE TITLE
Change chunk options, e.g. fig.width

### ISSUE THREAD

**Issue by mtennekes** [rstudio/rticles#42]
I'm preparing a JSS article, and want some figures to be at the same width as the text body, i.e. 6.125 inch.

I tried the following, but without desired result. I used the jss_article template.

``````
# Default figure size

```{r}
plot(1:10)
```

# Wide figure

```{r fig.width=6.125}
plot(10:1)
```
``````

Also setting global options didn't work:

``````
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=6.125) #doesn't seem to work
```
``````

Any ideas how to do this?

**Comment by mtennekes** [comment]
I figured out that it actually does work, i.e it determines the pdf sizes of the plots. However, the plot width in the pdf does not change, since there are no options set at the `\includegraphics` latex tag.
For the time being, I set the width in `\setkeys{Gin}{width=0.8\textwidth}` to `1.0` in the jss.cls file.

**Comment by yihui** [comment]
You can use `out.width=6.125`. See more about `fig.width` vs `out.width` at https://yihui.name/knitr/options/

As you can see, we don't really have enough bandwidth to answer questions here. Next time please do us a favor to [ask such questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead, and let us know the link if you don't get an answer in a few days. Thanks!
