### ISSUE TITLE
Rename the default branch from `master` to `main`

### ISSUE THREAD

**Issue by apreshill** [rstudio/rticles#420]
https://github.com/github/renaming

See also:

+ https://github.com/rstudio/bookdown/issues/1198
+ https://github.com/rstudio/distill/issues/390
+ https://github.com/rstudio/rmarkdown/issues/2181
+ https://github.com/rstudio/blogdown/issues/639
+ https://github.com/rstudio/blastula/issues/268

**Comment by cderv** [comment]
Replaced by #441
