### ISSUE TITLE
JSS template fails in rmarkdown 0.7

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rticles#43]
The template worked recently, but I may have had an old version of R Markdown. Now the tempalte returns the following error when run as is.

```
! Undefined control sequence.
l.48 \tightlist

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

**Comment by jjallaire** [comment]
I think all the rticles templates are going to need to be updated to
include the \tightlist macro (which pandoc defines in it's standard
template). This is the code that needs to be added:

https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/latex/default-1.14.tex#L127-L128

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rticles/commit/d1fa8547660d3d2fa68f9b4998c1e0bde0b1eb35

**Comment by englianhu** [comment]
I tried to create and knit a default JSS template, but the output is slides format with raw codes. Kindly look into this?
