### ISSUE TITLE
tufte ebook error

### ISSUE THREAD

**Issue by amitmohanty** [rstudio/rticles#44]
I installed RStudio/rticles and trying to "knit" the default template for "tufte e_book". I am getting the following error. Anyone has seen anything like this and if yes, did you get a work around?

---

<code>

processing file: Hello.Rmd
  |..                                 |   5%
  ordinary text without R code

  |....                               |  11%
label: setup (with options) 
List of 4
 $ echo   : logi FALSE
 $ message: logi FALSE
 $ cache  : logi FALSE
 $ include: logi TRUE

  |......                             |  16%
  ordinary text without R code

  |.......                            |  21%
label: unnamed-chunk-1 (with options) 
List of 2
 $ fig.margin: logi TRUE
 $ fig.cap   : chr "Sepal length vs. petal length, colored by species"

  |.........                          |  26%
  ordinary text without R code

  |...........                        |  32%
label: unnamed-chunk-2 (with options) 
List of 4
 $ fig.width    : num 10
 $ fig.height   : num 2
 $ fig.fullwidth: logi TRUE
 $ fig.cap      : chr "Full width figure"

  |.............                      |  37%
  ordinary text without R code

  |...............                    |  42%
label: unnamed-chunk-3 (with options) 
List of 1
 $ fig.cap: chr "Another figure"

  |.................                  |  47%
  ordinary text without R code

  |..................                 |  53%
label: unnamed-chunk-4 (with options) 
List of 1
 $ results: chr "asis"

  |....................               |  58%
  ordinary text without R code

  |......................             |  63%
label: amargintable (with options) 
List of 2
 $ results: chr "latex"
 $ echo   : logi FALSE

  |........................           |  68%
   inline R code fragments

  |..........................         |  74%
label: pandocDemo2 (with options) 
List of 1
 $ results: chr "asis"

  |............................       |  79%
   inline R code fragments

  |.............................      |  84%
label: kable (with options) 
List of 1
 $ results: chr "asis"

  |...............................    |  89%
   inline R code fragments

  |.................................  |  95%
label: fullwidthxtable (with options) 
List of 2
 $ results: chr "asis"
 $ echo   : logi FALSE

  |...................................| 100%
   inline R code fragments

Writing 8 Bibtex entries ... Quitting from lines 252-296 (Hello.Rmd) 
Error in utf8ToInt(x) : invalid UTF-8 string
Calls: <Anonymous> ... encoded_text_to_latex -> as.vector -> sapply -> lapply -> FUN -> utf8ToInt
Execution halted
</code>

**Comment by yihui** [comment]
Please try the **tufte** package instead: https://github.com/rstudio/tufte Thanks!
