### ISSUE TITLE
Unable to indent second line of references

### ISSUE THREAD

**Issue by ismayc** [rstudio/rticles#45]
Using the YAML bibliography specification and pandoc, I'm unable to indent the non-first lines of bibliography entries (aka hanging indent).  I've tried to set \bibhang but this does nothing to the resulting PDF document.  The only way I can get the non-first lines to indent is to not include the YAML bibliography specification and have biblatex take over the bibliography process in the template.tex file.  Unfortunately, this requires me to Compile PDF on the resulting .tex since RMarkdown doesn't appear to compile the bibliography when I Knit.

**Comment by ismayc** [comment]
An example of the issue is at https://github.com/ismayc/rticles/tree/master/inst/rmarkdown/templates/reed_thesis .

**Comment by crsh** [comment]
If I understand your question correctly, [this discussion](https://github.com/crsh/papaja/issues/37) may be helpful.

**Comment by ismayc** [comment]
Thanks.  I have tried this, but that shifts the entire citation to the left.  That works with a numbered style by keeping the number on the left, but I would prefer to use an APA style.  If there a way to apply this shift to non-first lines of citations?

**Comment by ismayc** [comment]
I meant "right" instead of "left."

**Comment by ismayc** [comment]
Something like this:

![screen shot 2015-10-14 at 9 38 21 am](https://cloud.githubusercontent.com/assets/9215614/10490715/5a95b4e6-7257-11e5-8241-f4c715b644e5.png)

**Comment by ismayc** [comment]
Thanks!  That works for me.

**Comment by ismayc** [comment]
With the caveat that a \noindent is needed to not have the first entry auto-indent.
