### ISSUE TITLE
Abstract in different file

### ISSUE THREAD

**Issue by ismayc** [rstudio/rticles#46]
Instead of having the abstract be inline in something like the R Journal template like this:

abstract: >
    An abstract of less than 150 words.

Is there a way to have the abstract be read in from an R Markdown file in a way like this?

abstract: abstract.Rmd

I understand that the LaTeX template files would need to be tweaked a bit if this is possible, but I'm not sure how to go about it.

**Comment by yihui** [comment]
You can probably do

```
abstract: >
"`r paste(readLines('abstract.Rmd'), collapse = '\n')`"
```

I didn't test it, though.

**Comment by ismayc** [comment]
It works if I delete the > and place it all on one line.  Thanks!

**Comment by yihui** [comment]
Great. Thanks for confirming that!

**Comment by ismayc** [comment]
I just tried it again and it works with the tab on the second line as well with the `>`.  Thanks for your help, @yihui!

**Comment by ismayc** [comment]
This is no longer working.  It now produces the error:

`pandoc: Could not parse YAML header: could not find expected ':' "source" (line 21, column 1)`

I created an `abstract.Rmd` file in the `skeleton` directory of an `rjournal_article` that contains the following text:

The preface pretty much says it all.

Second paragraph of abstract starts here.

Below is my `sessionInfo`.  

```
> sessionInfo()
R version 3.2.5 Patched (2016-04-17 r70499)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.1.0        R6_2.1.2          rsconnect_0.4.2   htmltools_0.3     tools_3.2.5      
 [6] withr_1.0.1       rticles_0.2       curl_0.9.6        yaml_2.1.13       memoise_1.0.0    
[11] rmarkdown_0.9.5.9 git2r_0.14.0      digest_0.6.9      devtools_1.10.0  
```

**Comment by ismayc** [comment]
I am only getting an abstract with multiple paragraphs in an abstract.Rmd file to work by changing 

abstract: >
`r paste(readLines('abstract.Rmd'), collapse = '\n')`

to

abstract: >
`r paste(readLines('abstract.Rmd'), collapse = ' ')`

and then including `\par` or `\newline` in the abstract.Rmd file after each paragraph.  Are there any better workarounds for this?

**Comment by yihui** [comment]
Changing `>` to `|` should work.
