### ISSUE TITLE
RJournal template inserts extra space before author names

### ISSUE THREAD

**Issue by rpruim** [rstudio/rticles#48]
![image](https://cloud.githubusercontent.com/assets/722231/10900191/f65d877a-81aa-11e5-9acd-4d797cc1fc9d.png)

**Comment by jjallaire** [comment]
We'd definitely take a PR for all of the issues reported.

**Comment by yihui** [comment]
It is no longer reproducible to me. Not sure when/how this was fixed. Feel free to reopen if the issue persists. Thanks!

![image](https://user-images.githubusercontent.com/163582/42333367-29069f9a-8040-11e8-8717-3a82b32fe174.png)
