### ISSUE TITLE
RJournal template can't handle some characters in R chunks

### ISSUE THREAD

**Issue by rpruim** [rstudio/rticles#49]
Most notably, `$` and `^` fail because of how knitr, pandoc, and latex interact with the RJournal requirement that code and output be placed in `Sinput` and `Soutput` environments.

See https://github.com/jgm/pandoc/issues/2493 for more discussion.

For many uses, this will be a blocking failure that will preclude authors from being able to use this template easily.

**Comment by rfhb** [comment]
This tool chain works for me: Adding the code below into the first chunk of an Rmd document, then pressing "Knit" in RStudio results is a fully rendered PDF file. Note the chunk output option escapes the problematic characters ($ becomes \$). This enables pandoc to convert to latex. The calls to pandoc and other operating system commands are made from the document output option. Perl is used to remove the escape ("\") again. Subsequently, the latex tools are run. Note to adapt the pandoc command to reference the specific template file for the intended journal. Maybe this hack is helpful for others wanting to use the templates. Thanks for knitr, rticles, pandoc! 

```
# workaround https://github.com/rstudio/rticles/issues/49
# see options on http://yihui.name/knitr/hooks/
#
knitr::knit_hooks$set(chunk = function(x, options) {
  #
  #cat(gsub("([$^%])", "\\\\\\1", "test%this$and^that"))
  gsub("([$^%])", "\\\\\\1", x)
  #
})
#
knitr::knit_hooks$set(document = function(x) {
  #
  fid  <- paste0(format(Sys.time(), "%Y-%m-%d_%H-%M-%S_file"))
  tmpf <- paste0(fid, ".md")
  texf <- paste0(fid, ".tex")
  auxf <- paste0(fid, ".aux")
  #
  cat(x, file = tmpf)
  #
  system(paste("pandoc +RTS -K512m -RTS", tmpf, "--to latex", "--from", 
               "markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash",
               "--output", texf, "--highlight-style tango", 
               "--latex-engine /Library/TeX/texbin/pdflatex", "--template",
               paste0(system.file(package = "rticles"), 
                     "/rmarkdown/templates/jss_article/resources/template.tex")))
  #
  system(paste("perl -p -i -e 's/\\\\([\\$\\%\\^])/$1/g'", texf))
  system(paste("pdflatex", texf))
  system(paste("bibtex",   auxf))
  system(paste("pdflatex", texf))
  system(paste("pdflatex", texf))
  file.remove(c(tmpf, texf, auxf, paste0(fid, c(".log", ".out", ".bbl", ".blg"))))
  # 
  x
  #
})
```

**Comment by yihui** [comment]
Fixed. Please try `devtools::install_github('rstudio/rticles')`. Note that it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by rfhb** [comment]
Very cool, many thanks for fixing and closing!
