### ISSUE TITLE
No graphics in JSS-articles

### ISSUE THREAD

**Issue by MarselScheer** [rstudio/rticles#5]
Inserting
```{r}
plot(sin)
```
in the JSS Rmd-template and compiling the document results in an error. The corresponding tex file contains markdown code for images.

**Comment by garthtarr** [comment]
Any update on this bug?  It seems odd to me that there is no problem including a plot the `output: rticles::rjournal_article` but it fails with `output: rticles::jss_article`.

**Comment by krlmlr** [comment]
This has hit me too. Does `install_github("rstudio/rticles#37")` work for you?
