### ISSUE TITLE
ACM template

### ISSUE THREAD

**Issue by khushnood** [rstudio/rticles#50]
First of all thanks for providing us such a good package. I just want to know how can i affiliate an author to a more than one institute. Sorry if my queation is silly because i am new in this field.

**Comment by yihui** [comment]
@ramnathv introduced the template in #8, so I'll defer the question to him. The maintainer of the **rticles** package is not a LaTeX expert, and not familiar with ACM articles, either...

**Comment by ramnathv** [comment]
@khushnood The default template only supports one institution per author. A workaround could be to provide both institution addresses in the same YAML field separated by a comma. Hope this helps.

https://github.com/ramnathv/rticles/blob/master/inst/rmarkdown/templates/acm/resources/template.tex#L40-L46

**Comment by khushnood** [comment]
Although I started using Latex now because of these problems, but thanks to both of you.  :)
