### ISSUE TITLE
PNAS is missing extarticle

### ISSUE THREAD

**Issue by alecristia** [rstudio/rticles#510]
The solution is simply to get it from here: http://tug.ctan.org/tex-archive/macros/latex/contrib/extsizes/extarticle.cls

**Comment by cderv** [comment]
The PNAS format requires installing `extsizes` package from CTAN. Using **tinytex** with R Markdwn, it should install automatically if missing. For example, I got this by rendering
````
tlmgr.pl: package repository https://mirrors.nxthost.com/ctan/systems/texlive/tlnet (not verified: pubkey missing)
[1/1, ??:??/??:??] install: extsizes [12k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/chris/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr.pl: command log updated: C:/Users/chris/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr-commands.log
````

You can install manually using `tinytex::tlmgr_install("extsizes")` or using `tlmgr` at command line directly (or install the package fro your distribution (MikTeX maybe). 

Anyway, format depends on some CTAN package that needs to be installed. Error log will tell you what is missing if you don't rely on automatic installation. 

We don't usually add `.cls` files in the templates when they can be available through a CTAN package. 

Thank for reporting though.
