### ISSUE TITLE
Deprecate `rjournal_article()` in favor of **rjtools** ?

### ISSUE THREAD

**Issue by cderv** [rstudio/rticles#522]
Hi ! 

@mitchelloharawild I did the update of #517 based on **rjtools** bundled file. 

In https://github.com/rjournal/rjtools/issues/61#issuecomment-1459141584 you raise the good question of `rjournal_article()` future now that **rjtools** exists. But you never opened an issue in this repo to ask here

> I am unsure if they plan to continue providing the rjournal article format in their package as we encourage submissions in the rjtools HTML/PDF format.

I am ok with adding a deprecation warning inside **rticles** package to explain that now **rjtools** should be used. Initially we did the format as there was none, there is no point in keeping it inside **rticles** if it is not to be used to submit to R Journal

What should we do about this ?

_Originally posted by @cderv in https://github.com/rstudio/rticles/issues/517#issuecomment-1488703991_

**Comment by cderv** [comment]
@dicook @mitchelloharawild what are your thoughts on this, considering **rjtools** seems to be the recommended way now ?

**Comment by dicook** [comment]
Definitely would vote “yes"

> On 2 May 2023, at 7:13 pm, Christophe Dervieux ***@***.***> wrote:
> 
> 
> @dicook @mitchelloharawild what are your thoughts on this, considering rjtools seems to be the recommended way now ?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

cheers,
Di


---
Dianne Cook
***@***.***
