### ISSUE TITLE
PNAS template not knitting :(

### ISSUE THREAD

**Issue by matanmazor** [rstudio/rticles#562]
Hi there,

When trying to knit the PNAS template, I get the following error messaage:

> ! Package babel Error: Unknown option 'english'. Either you misspelled it
> (babel)                or the language definition file english.ldf
> (babel)                was not found.
> (babel)                There is a locale ini file for this language.
> (babel)                If it’s the main language, try adding `provide=*'
> (babel)                to the babel package options.
> 
> Error: LaTeX failed to compile paper_PNAS.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See paper_PNAS.log for more info.
> Execution halted

Session info:

> R version 4.3.2 (2023-10-31 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 11 x64 (build 22631), RStudio 2023.12.0.369
> 
> 
> Locale:
>   LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8
>   LC_NUMERIC=C                            LC_TIME=English_United Kingdom.utf8    
> 
> time zone: Europe/London
> tzcode source: internal
> 
> Package version:
>   base64enc_0.1.3   bslib_0.6.1       cachem_1.0.8      cli_3.6.1         digest_0.6.33     ellipsis_0.3.2    evaluate_0.23     fastmap_1.1.1    
>   fontawesome_0.5.2 fs_1.6.3          glue_1.6.2        graphics_4.3.2    grDevices_4.3.2   highr_0.10        htmltools_0.5.7   jquerylib_0.1.4  
>   jsonlite_1.8.7    knitr_1.45        lifecycle_1.0.4   memoise_2.0.1     methods_4.3.2     mime_0.12         R6_2.5.1          rappdirs_0.3.3   
>   rlang_1.1.1       rmarkdown_2.26    sass_0.4.8        stats_4.3.2       tinytex_0.49      tools_4.3.2       utils_4.3.2       xfun_0.40        
>   yaml_2.3.7       
> 
> Pandoc version: 3.1.1

(using the development version and upgraded all packages).

**Comment by cderv** [comment]
Sorry for the delay on that one. 

Right now I can't reproduce with latest dev version of **rticles** soon to be release, and our test of building the template is passing. 

Please do reopen if you have a custom example to share. Thanks !
