### ISSUE TITLE
Representation of list-objects in JSS

### ISSUE THREAD

**Issue by MarselScheer** [rstudio/rticles#6]
Inserting

``` r
L = list(a = 10)
L
```

and

``` r
L$a
```

in a JSS Rmd-template results in strange "CodeInput" and "CodeOutput" full of \textbackslash{}.

**Comment by yihui** [comment]
Fixed, and it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/
