### ISSUE TITLE
RJournal bibliography handling

### ISSUE THREAD

**Issue by spedygiorgio** [rstudio/rticles#71]
I tried to use the bibliography: item in yaml header but is does not work.... 

[RJournal.zip](https://github.com/rstudio/rticles/files/295963/RJournal.zip)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report, and apologies for the late action!

**Comment by spedygiorgio** [comment]
You welcome

 

Da: Yihui Xie <notifications@github.com> 
Inviato: giovedì 5 luglio 2018 18:24
A: rstudio/rticles <rticles@noreply.github.com>
Cc: Giorgio Alfredo Spedicato <spedygiorgio@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [rstudio/rticles] RJournal bibliography handling (#71)

 

Should be fixed now. Thanks for the report, and apologies for the late action!
