### ISSUE TITLE
JSS bibliography style not honoured

### ISSUE THREAD

**Issue by richierocks** [rstudio/rticles#73]
When using `rticles::jss_article` to create an Article for the Jounral of Statistical Software, there are a few problems with how the contents of the bibliography appear.

Firstly, uses of `\pkg` and `\proglang` in the bibliography style don't have an effect on the style of the resulting text.

Secondly, JSS reference styling isn't quite right (possibly completely ignored?).  For example, in JSS style, the URL to an R package should be prefixed with "URL", but this isn't the case.

Thirdly, in the main text, the citation should be a hyperlink to the reference at the end of the article.  These hyperlinks don't occur.

Reproducible example atttached:

[biblio-problem.zip](https://github.com/rstudio/rticles/files/318378/biblio-problem.zip)

**Comment by richierocks** [comment]
I should probably specify more about what I see and what I expect in the attachment.

The `bibliography.bib` file contains the line

    title = {\pkg{rticles}: Article Formats for \proglang{R} Markdown}

In the Bibliogrpahy section of `biblio-problem.pdf` I expect to see that the package name `rticles` is in bold, and the programming language `R` has a different font.  It appears that the `\pkg` and `\proglang` commands are ignored.

Again in the Bibliogrpahy section of `biblio-problem.pdf`, I expect the URL  https://CRAN.R-project.org/package=rticles to be prefixed with the text "URL".

Thirdly, in the Introduction section, I expect the text "Allaire et al. 2016" to be a hyperlink to the corresponding reference in the Bibliography section.

**Comment by yihui** [comment]
I believe this has been fixed last year via 65a66b513f8e7204ecb92b116758d4834570184b. Could you try the latest version of the package here? Thanks!
