### ISSUE TITLE
rjournal_article doesn't work with rmarkdown::render() with defined output folder or file

### ISSUE THREAD

**Issue by haozhu233** [rstudio/rticles#74]
Hello, I just came across this weird bug with `rjournal_article` that if you use `rmarkdown::render("your_rmd_file.Rmd", output_dir = "something_else/")`, the final pdf file will not be copied to the output directory. 

I assume this bug happens because the name of the pdf file has been changed to "RJwrapper.pdf" by default so the `output_dir` option cannot recognize it?

A reproducible sample (it will create some files in your pkg folder.... )
(you will need to create a "test" folder under your working directory)

```
file_location <- try(
  render(
    system.file("rmarkdown/templates/rjournal_article/skeleton/skeleton.Rmd", package = "rticles"), 
    output_dir = "test/"
  )
)

file_location
```

If you want to use it with `output_file` it will throw an error message like

```
! Undefined control sequence.
l.5 \maketitle

pandoc: Error producing PDF
Error : pandoc document conversion failed with error 43
```

I'm using Rstudio Priview and the CRAN version of `rticles` (0.2) and `rmarkdown` (0.9.6.14) but the problem still exist in the github version of `rticles` (just tried it).

PS: Everything else in `rticles` works fine.

**Comment by yihui** [comment]
I'm afraid you just cannot use `output_file` or `output_dir` with this output format. Sorry.

Your best bet is to render the PDF, and move/rename it afterwards.
