### ISSUE TITLE
pnas-new.cls not found

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rticles#89]
Hi,

If I install from github using install_github, then try to use pnas_template within RStudio, I get the following error:

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS fairness-paper.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output fairness-paper.pdf --template /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rticles/rmarkdown/templates/pnas_article/resources/template.tex --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --bibliography bibliography.bib --filter /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc-citeproc 
! LaTeX Error: File `pnas-new.cls' not found.

My pnas-new.cls file is installed in /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rticles/rmarkdown/templates/pnas_article/resources/, which seems to be where it should be.

Not sure if this is a bug or my own problem.

David

**Comment by cboettig** [comment]
@hughjonesd you may not have a complete / up-to-date tex installation?  can you provide some more details on your tex environment?

**Comment by hughjonesd** [comment]
I think this must be true: just upgraded to uptodate TexLive 2016, and the problem no longer appears.
