### ISSUE TITLE
Honour header-includes

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rticles#90]
It would be nice if these formats would honour the header-includes metadata in .Rmd files. This could be done by adding

```
$for(header-includes)$                                                                                                 
$header-includes$                   
$endfor$
```

to the relevant templates.

**Comment by lioumens** [comment]
@hughjonesd Thanks! I thought I was going insane when my header-include statements were not working.

**Comment by jjallaire** [comment]
@yihui Would it be straightforward for us to add these or are there side effects we are worried about? (seems like if no one uses the the in_header as it stands we wouldn't break anyone by doing this).

@hughjonesd I believe this makes sense. Sometimes template authors don't think to add this but they certainly should. We'd certainly welcome a PR with these additions though!

**Comment by yihui** [comment]
I believe it should be safe to add the support to the existing templates in this package.

**Comment by jjallaire** [comment]
Okay, @hughjonesd could you give us a PR for this?

**Comment by hughjonesd** [comment]
Can do.

David
