### ISSUE TITLE
add template for IEEE Transactions

### ISSUE THREAD

**Issue by Emaasit** [rstudio/rticles#95]
Can we add IEEE Transactions; another major journal for a lot of R Users. Latex template can be found on the confere site at http://www.ieee.org/conferences_events/conferences/publishing/templates.html

Forked this repo and started working on it on branch: https://github.com/emaasit/rticles/tree/ieee

**Comment by Emaasit** [comment]
Submitted pull request https://github.com/rstudio/rticles/pull/97

**Comment by espinielli** [comment]
In order to have figures mixed with text I had to comment out the `\usepackage[endfloat]`.
I haven't found `endfloat` in IEEETrans template...at least not hardcoded.
